      <div class="row">
        <div class="col-sm-20 col-md-20 clearfix">
          <div class="ctgry-headpanel clearfix">
            <div class="categoryheading">
              <h4>About Us</h4>
            </div>

          </div>

          <div class="row">
            <div class="col-sm-20">
              <div class="aboutright">
                <div class="aboutus-image">
                  
                  <img class="img-responsive" alt="$about_us_page$" src="$about_us_page$"/>
                                </div>
                <div class="aboutpagecontent">
                  <p>Wagner Electronic Services is an independent Australian organisation dedicated to the Electronic Industry.</p>

                  <p>For the past 25+ years we have maintained a leading reputation of high quality products and accessories to the Custom Audio Visual Installation, Communications, DATA, Consumer Electronics, Engineering and Servicing industries.</p>

                  <p>Our Products are sourced globally from reliable and internationally known manufacturers and are of the highest quality. Australia wide overnight shipping is available as well as in store pick up.</p>

                </div>
              </div>
            </div>
          </div>


        </div>

      </div>
<!--<table width="778" border="0" cellpadding="0" cellspacing="0">
 
  <tr>
    <td width="778" height="38" valign="top" align="left">
      <table width="778" border="0" cellpadding="0" cellspacing="0">
       
        <tr>
          <td width="761" height="24" valign="top"  style="font-size:12px;">
            <span class="txt_11">
              <strong>
                <a href="/Home.aspx" class="txt_11" >Home</a>
              </strong>
            </span> / About Us
          </td>
          <td width="17">&nbsp;</td>
        </tr>
        <tr>
          <td height="14" valign="top" class="bdr_bottom" ></td>
          <td ></td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td valign="top" align="left">
      <table width="720" border="0" cellpadding="0" cellspacing="0">
       
        <tr>
          <td width="720" height="112" valign="top">
            <table width="720" border="0" cellpadding="0" cellspacing="0">
            
              <tr>
                <td width="583" height="84" valign="top">
               
                  <h1 class="bold_h1tag_au">About Us</h1>
                  <p class="txt_aboutus">Wagner Electronic Services is an independent Australian organisation dedicated to the Electronic Industry.</p>
                  
                  <p class="txt_aboutus">For the past 25+ years we have maintained a leading reputation of high quality products and accessories to the Custom Audio Visual Installation, Communications, DATA, Consumer Electronics, Engineering and Servicing industries.</p>
                 
                  <p class="txt_aboutus">Our Products are sourced globally from reliable and internationally known manufacturers and are of the highest quality. Australia wide overnight shipping is available as well as in store pick up.</p>
                 
                </td>
                <td width="137" rowspan="2">
                  <img src="images/icon23.png" width="99" height="112" />
                </td>
              </tr>
             
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
</table>-->