
<div class="form-group clearfix">
  <div >
  
     

    <a onclick="getValue_ps(this);" class="sidebar_button" style="cursor:default" ping="$TBT_REWRITEURL$/ps/" rel="ps.aspx?&amp;id=0&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$">$TBW_ATTRIBUTE_NAME$ ($TBW_PRO_CNT$)</a>
  </div>
</div>

