<div class="yourselect-list">
  <div class="selectlist-inner">
    <a  onclick="getValue_breadcrumb(this);" style="cursor:default"  ping="/$TBT_REWRITEURL$" rev="/$TBT_URL$">$TBW_ITEM_NAME$</a>
  </div>
  <div class="close-selected">
    <a ping="/$TBT_REMOVEURL$"  style="cursor:default"  onclick="getValue_breadcrumb(this);" rev="/$TBT_URL_REMOVE$" class="remove">

      <img src="$CDN$images/close2.png"/>
    </a>
  </div>
   
    <br/>
  
</div>