
<!--<input type="submit"  class="list-group-item light_bg_input"   style="width:100%"  value="$TBW_ATTRIBUTE_NAME$ ($TBW_PRO_CNT$)" onclick="OnclickTab('txt$TBW_ATTRIBUTE_INPUT$');" />
<input type="hidden" id="txt$TBW_ATTRIBUTE_INPUT$" name="txt$TBW_ATTRIBUTE_INPUT$" value="$ORG_EA_PATH$@@$TBW_ATTRIBUTE_TYPE$@@$TBW_ATTRIBUTE_NAME_NEW$" >

</input>-->
<a onclick="getValue_PL_MS(this);" class="sidebar_button" style="cursor:default" ping="$TBT_REWRITEURL$/mpl/" rel="pl.aspx?&amp;id=0&amp;pcr=$TBW_PARENT_CATEGORY_ID$&amp;cid=$TBW_CATEGORY_ID$&amp;tsb=$TBW_BRAND$&amp;tsm=$TBW_MODEL$&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$">
  $TBW_ATTRIBUTE_NAME$ ($TBW_PRO_CNT$)
  $TBW_OPTION_CATEGORY_ID$
</a>
