<!--<li><a id="PSTYPE$TBW_ATTRIBUTE_TYPE$"  href="$TBT_REWRITEURL$/mps/"  rel="/mps.aspx?&amp;id=0&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$">$TBW_ATTRIBUTE_NAME$</a></li>-->

<a id="PSTYPE$TBW_ATTRIBUTE_TYPE$" onclick="getValue_ps_MS(this);" class="sidebar_button" style="cursor:default"  ping="$TBT_REWRITEURL$/mps/"  
   rel="/mps.aspx?&amp;id=0&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$
   &amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;
   byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$" class="list-group-item light_bg">
  $TBW_ATTRIBUTE_NAME$</a>
<!--<input type="submit"   class="list-group-item light_bg_input"   value="$TBW_ATTRIBUTE_NAME$ ($TBW_PRO_CNT$)"        style="width:100%"
        onclick="OnclickTab('txt$TBW_ATTRIBUTE_INPUT$');"></input>
<input type="hidden" id="txt$TBW_ATTRIBUTE_INPUT$" name="txt$TBW_ATTRIBUTE_INPUT$" value="$ORG_EA_PATH$@@$TBW_ATTRIBUTE_TYPE$@@$TBW_ATTRIBUTE_NAME_NEW$" >-->

</input>
