<h3 class="title3aLeft padht">$TBT_ATTRIBUTE_TITLE$</h3><div class="submenu"><ul>$TBWDataList:{$it.TBWDataListItem$}$</ul><div class="submenuhide" id="submenuhide$TBT_MENU_ID$"><ul>$TBWDataList1:{$it.TBWDataListItem1$}$</ul></div><div  class="show_hide" id="show1" onclick="showsubmenu($TBT_MENU_ID$);dsp(this)" ><span class="dspchar">+ Show more options</span></div></div><div class="clearall"></div>

<!--<div class="panel-heading" role="tab" id="headingOne">
  <h4 class="panel-title">
    <a role="button" data-toggle="collapse" data-parent="#accordion" href="#flt1" aria-expanded="true" aria-controls="collapseOne">
      <i class="more-less glyphicon glyphicon-plus"></i>
      >$TBT_ATTRIBUTE_TITLE$
    </a>
  </h4>
</div>
<div id="flt1" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
  <div class="panel-body">
    $TBWDataList:{$it.TBWDataListItem$}$
  </div>
</div>-->
