<li>
  <div class="fil-inner">
    <span class="fil-item-type"> $TBW_ITEM_TYPE$</span>
    <span class="fil-item-name">
      <a id="YHBC$TBT_ATTRIBUTE_TYPE$"  onclick="getValue_breadcrumb(this);" ping="$TBT_REWRITEURL$"
         rel="/$TBT_URL$"  title="TBW_ITEM_Title"
         style="background: none repeat scroll 0 0 rgba(0, 0, 0, 0); border-bottom: none;color: #333;display: block;float: left;font-size: 12px;line-height: 15px;padding: 0;" >$TBW_ITEM_NAME$</a>
    </span>
  </div>
  <div class="fil-iten-cancel">
    <a id="YHRBC$TBT_REM_ATTRIBUTE_TYPE$"   ping="/$TBT_REMOVEURL$"  style="cursor:default"   title="TBW_ITEM_Title" onclick="getValue_breadcrumb(this);"
        rel="/$TBT_URL_REMOVE$" class="fil-close">
      <img src="$CDN$images/MicroSiteimages/plus-gray.png" />
            </a>
  </div>
</li>