
<div>

VIP Vision is the premier IP surveillance solution for enterprise and 
commercial applications. We believe that for CCTV to truly grant peace of mind,
it must function seamlessly with your existing business operations. 
The VIP Vision range delivers powerful, scalable IP CCTV systems,
with an emphasis on functionality, ease of use and ease of installation across 
the range. VIP Vision has over 2,000 professionals in research and development,
they are at the forefront of advanced surveillance technologies. 
Their constant pursuit of innovation delivers cutting edge products
with high quality, performance and reliability. 
</div>