<div class="bs-example col-lg-20 subfamily" data-example-id="bordered-table"> 
  <table class="table table-bordered">
    <thead>
      <tr class="greyborder">
        <th width="100" class="white_color no-bdr">
          <img class="thead_img lazy" data-original="$CDNROOT$prodimages$TBT_TFWEB_IMAGE1$" alt="$TBT_FAMILY_NAME$"/>
        </th>
        <th class="white_color nolft-bdr">
          <h3>$TBT_FAMILY_NAME$</h3>
          <h5 class="font_normal">
            <strong>$TBT_SHORT_DESCRIPTION$</strong>
          </h5>
          <p> $TBT_SHORT_DESCRIPTION1$</p>
          <p>$TBT_SHORT_DESCRIPTION2$</p>
          <p> $TBT_SHORT_DESCRIPTION3$</p>
          <p>$TBT_SHORT_DESCRIPTION4$</p>
          <p>$TBT_DESCRIPTIONS$</p>
        </th>
      </tr>
    </thead>
  </table>
</div>
