<div class="col-md-20">
  <div class="row">
    <div class="row product-info">
      $Generateparentfamilyhtml$
      <div class="col-sm-20">
        <div class="tabs">
          <ul id="myTab" class="nav nav-tabs">
            <li class="active">
              <a href="#profile">Products</a>
            </li>
            <li>
              <a href="#tab2">Ask a Question</a>
            </li>
            <li>
              <a href="#tab3">Bulk Buy / Project Price</a>
            </li>
            <li >
              <a href="#downloads">Downloads</a>
            </li>
            <li>
              <a href="#shipping">Shipping Info</a>
            </li>
          </ul>
          <div class="tab-content">
            
            <div id="profile" class="tab-pane active">
            
             
              <div id="innertable" class="inner-table">
                $ST_Familypage$
                         
                <div class="text-center" id="tblload" style="display:none">
                  <img src="$CDN$images/MicroSiteimages/bigLoader.gif" class="margin_bottom_15" alt=""/>
                  <br>Loading Data.. Please Wait..</br>
                </div>
                
                
              </div>
            </div>
            
            <div id="tab2" class="tab-pane">
              <div class="text-center" id="askaquestionLoad" style="display:none">
                <img src="$CDN$images/MicroSiteimages/bigLoader.gif" class="margin_bottom_15" alt=""/>
                <br>Loading Data.. Please Wait..</br>
              </div>
             
            </div>
            $ST_BulkBuyPP$
            <div id="tab3" class="tab-pane">
              <div class="text-center" id="bulkbuyLoad" style="display:none">
                <img src="$CDN$images/MicroSiteimages/bigLoader.gif" class="margin_bottom_15" alt=""/>
                <br>Loading Data.. Please Wait..</br>
              </div>

            </div>
<div id="downloads" class="tab-pane">
              <div class="text-center" id="bulkbuyLoad" style="display:none">
                <img src="$CDN$images/MicroSiteimages/bigLoader.gif" class="margin_bottom_15" alt=""/>
                <br>Loading Data.. Please Wait..</br>
              </div>
$DownloadST_new$
            </div>


            <div id="shipping" class="tab-pane">
              <div class="text-center" id="shippingLoad" style="display:none">
                <img src="$CDN$images/MicroSiteimages/bigLoader.gif" class="margin_bottom_15" alt=""/>
                <br>Loading Data.. Please Wait..</br>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
</div>

