<div class="contactpge_info">
  <h4>Wagner Electronic Services</h4>
  <div class="contactinfo-box clearfix">
    <h5 class="greybold">Business Hours </h5>
    <h5 class="bluetxt">8.30AM - 5PM Monday to Friday</h5>
    <h5 class="bluetxt">9.00AM - 4PM Saturday</h5>

  </div>
  <div class="contactinfo-box clearfix">
    <h5 class="greybold">Phone </h5>
    <h5 class="bluetxt">
      <a href="tel:(+61) 02 9798 9233" itemprop="telephone" style="color:inherit;text-decoration:none;">(+61) 02 9798 9233</a></h5>
  </div>

  <div class="contactinfo-box clearfix">
    <h5 class="greybold">Fax </h5>
    <h5 class="bluetxt" itemprop="faxNumber">(+61) 02 9798 0017</h5>
  </div>

  <div class="contactinfo-box clearfix">
    <h5 class="greybold">Email </h5>
    <h5 class="bluetxt">
      <a href="mailto:sales@wagneronline.com.au">sales@wagneronline.com.au</a>
    </h5>

  </div>

  <div class="contactinfo-box clearfix" itemtype="http://schema.org/PostalAddress" itemscope="" itemprop="address"  style="cursor:pointer;" >

      <h5 class="greybold">Address </h5>
    <a href="https://www.google.com/maps/dir/New+Orleans,+Louisiana/Houston,+Texas/&mapclient=embed&cid=329406495118348836" target="_blank" style="color:inherit;text-decoration:none;" title="Click to Larger Map">
    <!--<a href="https://maps.google.com/maps?ll=-33.890457,151.129084&z=16&t=m&hl=en-US&gl=US&mapclient=embed&cid=329406495118348836" target="_blank" style="color:inherit;text-decoration:none;" title="Click to Larger Map">-->
      <h5 class="bluetxt"  itemprop="streetAddress">138 liverpool Road,</h5>
      <h5 class="bluetxt"  itemprop="addressLocality">Ashfield, NSW, 2131,</h5>
      <h5 class="bluetxt"  itemprop="Addresscountry">Australia</h5>
    </a>
    <!--<a style="color:#0069b2;cursor:pointer;" onclick="showmap();">View Map</a>-->
  </div>
  <div class="clearfix" style="height:10px"></div>
<div class="contactinfo-box clearfix" id="gmap" style="display:block;">
  <address>
    Wagner Electronic Services, 138 Liverpool Road, Ashfield NSW 2131,Australia
  </address>
</div>
  <!--<div class="contactinfo-box clearfix" id="gmap">
    <div id="googleMap" style="height:380px;">
      -->
  <!--<iframe width="425px" height="350px" frameborder="0" scrolling="no"  marginheight="0" marginwidth="0"   src="https://maps.google.com/maps?&amp;q="+ encodeURIComponent( Wagner Electronic Services, 138 Liverpool Road, Ashfield NSW 2131 ) +"&amp;output=embed"></iframe>--><!--

    </div>
  </div>-->
  
</div>
<!--<div itemscope="" itemtype="http://schema.org/LocalBusiness" class="txt_aboutus"><img src="images/icon22.png" alt="" width="126" height="114" /><br/><span itemprop="name" style="font-weight:bold;">Wagner Electronic Services</span><br/><div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><span itemprop="streetAddress">138 Liverpool Road</span>,<br/><span itemprop="addressLocality">Ashfield</span>,<span itemprop="Addressregion">NSW</span>, <span itemprop="postalCode">2131</span><br/><span itemprop="Addresscountry">Australia</span></div>
  <br/><div>Ph: <span itemprop="telephone">(+61) 02 9798 9233</span><br/>Fax: <span itemprop="faxNumber">(+61) 02 9798 0017</span><br/>Email: <a href="mailto:sales@wagneronline.com.au" style="text-decoration: underline !important;">sales@wagneronline.com.au</a><br/>Website: <a href="https://www.wagneronline.com.au" target="_blank" style="text-decoration: underline !important;">www.wagneronline.com.au</a>
  </div><div><p class="txt_aboutus">
      <strong>Business Hours:</strong><br/>
      8.30AM - 5PM Monday to Friday <br/>
      9.00AM - 4PM Saturday <br/>
    </p>
  </div>
</div>-->

