

  <div class="row ">
    <div class="home_heading"  style="margin-top:15px">&nbsp;&nbsp;&nbsp;POPULAR PRODUCTS</div>
    <div id="home-product">
      $TBWDataList:{ $it.TBWDataListItem$}$
    </div>
    <div class="clearfix"></div>
     <div class="home_heading"  style="margin-top:15px">&nbsp;&nbsp;&nbsp;Reviews</div>
    <div class="reviewmgr-stream" data-include-empty="false" data-review-limit="5" data-url="https://reviewr.app/wagneronline/"></div><script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.reviewmgr.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document, "script", "reviewmgr-wjs");</script>
  </div>

