<td height="295" valign="top" >
  <div class="box_pro_high1" style="width:185px;height:295px;padding:5px">
    <a href="$TBT_REWRITEURL$/pd/" >
      <div style="display:table-cell; vertical-align:middle; width:180px;height:100px;"  align="center">
        <!--<img src="/prodimages$TBT_TWEB_IMAGE1$" name="" maxheight="100px"  maxwidth="100px"  style="display: block;margin-left: auto;margin-right: auto" />-->
         <!--<img class="lazy" data-original="/prodimages$TBT_TWEB_IMAGE1$"   maxheight="100"  maxwidth="100" />-->
        <!--<img class="lazy" data-original="/prodimages$TBT_TWEB_IMAGE1$" style="display: block;margin-left: auto;margin-right: auto" maxheight="100" maxwidth="100" />-->
      </div>
    </a>
    <div class="familyheader" style="height:30px;">
      <a href="$TBT_REWRITEURL$/pd/" title="$TBT_FAMILY_NAME$" >
        <storng>$TBT_FAMILY_NAME$</storng>
      </a>
    </div>
    <p style="height:36px;">
      $TBT_DESCRIPTIONS$
    </p>
    <div class="viewprodetails12">
      <a href="$TBT_REWRITEURL$/pd/" title="$TBT_FAMILY_NAME$"  >
        <strong>Order No: $TBT_CODE$</strong>
        <br/>
        <strong> Cost: &amp;#36;$TBT_YOURCOST$</strong>
      </a>      
    </div>
    <div style="margin-top:0px;margin-left:45px;">
      $if(TBT_ECOMENABLED)$$if(TBT_STOCK_STATUS_2)$<br/>
      <a onClick="productbuy('txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$','$TBT_PRODUCT_ID$');" style="cursor: pointer;" class="homebut_buy1">
        $endif$$endif$
      </a>
    </div>
  </div>
  
</td>