<div class="row">
    <div id="home-product" class="clearfix">
      <div class="block_row clearfix" >
      <div class="pro_block">
        <div class="block_proname">
          <h5>
            <a  style="text-decoration:none;"  href="/face-masks/pl/">Face Masks</a>
          </h5>
        </div>
        <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
          <a href="/face-masks/pl/">
            <img class="img-responsive lazy" src="$CDN$images/btp-btn-facemasks.jpg" data-original="$CDN$images/btp-btn-facemasks.jpg" alt="Face Masks" width="245px" height="120px" style="margin:auto;max-height:180px" />
          </a>
        </div>
      </div>
      <div class="pro_block" >
        <div class="block_proname">
          <h5>
            <a style="text-decoration:none;" href="/gloves/pl/" >Gloves</a>
          </h5>
        </div>
        <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
          <a href="/gloves/pl/">
            <img class="img-responsive lazy" src="$CDN$images/btp-btn-handgloves.jpg" data-original="$CDN$images/btp-btn-handgloves.jpg" alt="Gloves" width="245px" height="120px" style="margin:auto;max-height:180px" />
          </a>
        </div>
      </div>
      <div class="pro_block" >
        <div class="block_proname">
          <h5>
            <a style="text-decoration:none;" href="/hand-sanitiser-cleaning/pl/" >Hand Sanitiser & Cleaning</a>
          </h5>
        </div>
        <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
          <a href="/hand-sanitiser-cleaning/pl/">
            <img class="img-responsive lazy" src="$CDN$images/btp-btn-handsanitiser.jpg" data-original="$CDN$images/btp-btn-handsanitiser.jpg" alt="Hand Santiziers" width="245px" height="120px" style="margin:auto;max-height:180px" />
          </a>
        </div>
      </div>
      
    
      <div class="pro_block" >
        <div class="block_proname">
          <h5>
            <a style="text-decoration:none;" href="/thermometers/pl/" >Thermometers</a>
          </h5>
        </div>
        <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
          <a href="/thermometers/pl/">
            <img class="img-responsive lazy" src="$CDN$images/btp-btn-thermometers.jpg" data-original="$CDN$images/btp-btn-thermometers.jpg" alt="Thermometer" width="245px" height="120px" style="margin:auto;max-height:180px" />
          </a>
        </div>
      </div>
      <div class="pro_block" >
        <div class="block_proname">
          <h5>
            <a style="text-decoration:none;"  href="/soho-headsets/work-from-home-video-conferencing/pl/">SOHO Headsets</a>
          </h5>
        </div>
        <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
          <a href="/soho-headsets/work-from-home-video-conferencing/pl/">
            <img class="img-responsive lazy"  src="$CDN$images/btp-btn-headset.jpg" data-original="$CDN$images/btp-btn-headset.jpg" alt="SOHO Headsets" width="245px" height="120px" style="margin:auto;max-height:180px" />
          </a>
        </div>
      </div>
        <div class="pro_block" >
          <div class="block_proname">
            <h5>
              <a style="text-decoration:none;"  href="/soho-keyboard-and-mouse/work-from-home-video-conferencing/pl/">SOHO Keyboard and Mouse</a>
            </h5>
          </div>
          <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
            <a href="/soho-keyboard-and-mouse/work-from-home-video-conferencing/pl/">
              <img class="img-responsive lazy"  src="$CDN$images/btp-btn-keyboard-mouse.jpg" data-original="$CDN$images/btp-btn-keyboard-mouse.jpg" alt="SOHO Keyboard and Mouse" width="245px" height="120px" style="margin:auto;max-height:180px" />
            </a>
          </div>
        </div>
        <div class="pro_block" >
          <div class="block_proname">
            <h5>
              <a style="text-decoration:none;"  href="/soho-monitors/work-from-home-video-conferencing/pl/">SOHO Monitors</a>
            </h5>
          </div>
          <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
            <a href="/soho-monitors/work-from-home-video-conferencing/pl/">
              <img class="img-responsive lazy"  src="$CDN$images/btp-btn-monitor.jpg" data-original="$CDN$images/btp-btn-monitor.jpg" alt="SOHO Monitors" width="245px" height="120px" style="margin:auto;max-height:180px" />
            </a>
          </div>
        </div>
        <div class="pro_block" >
          <div class="block_proname">
            <h5>
              <a style="text-decoration:none;"  href="/soho-web-cams/work-from-home-video-conferencing/pl/">SOHO Web Cams</a>
            </h5>
          </div>
          <div class="block-img animateOnScroll animated zoomIn" data-offset-top="200" data-timeout="0" data-animation-type="zoomIn">
            <a href="/soho-web-cams/work-from-home-video-conferencing/pl/">
              <img class="img-responsive lazy"  src="$CDN$images/btp-btn-webcam.jpg" data-original="$CDN$images/btp-btn-webcam.jpg" alt="SOHO Web Cams" width="245px" height="120px" style="margin:auto;max-height:180px" />
            </a>
          </div>
        </div>
        
      </div>
  
    </div>
  </div>
