
  <div class="left_filter">
 
      <h4>Brand & Model</h4>
      <div class="brndmodal_wrap subject">
        <input type="hidden" name="subject" value="Brand" />
        <li class="dropdown" id="brandmodal">
          <a href="#" >
            $Brand$
          </a>
          <!--<div class="dropdown-menu">-->
            <ul class="">
       

              $TBWDataList:{$it.TBWDataListItem$}$
            </ul>
          <!--</div>-->
        </li>
      </div>


      <div class="brndmodal_wrap subject">
        <!--<span class="selected">Brand</span> -->
        <input type="hidden" name="subject" value="Brand" />
        <li class="dropdown" id="brandmodal">
          <a href="#" >
            Model
          </a>
          <!--<div class="dropdown-menu">-->
            <ul class="">
            <!--<li id="general" class="selected">
              <a href="">Modal</a>
            </li>-->
              $TBWDataList1:{$it.TBWDataListItem$}$
            </ul>
          <!--</div>-->
        </li>
      </div>
 
  </div>

