<span typeof="v:Breadcrumb" class="margin_right16" >
  <a href="$TBT_REWRITEURL$"  class="gray_40 padding_right15" property="v:title" rel="v:url">$TBT_LINKNAME$ </a>
  <input type="hidden" id="hflastbcurl" name="hflastbcurl" value="/$lastvalue$"/>
  <a onclick="getValue_breadcrumb_(this);" style="cursor:default"  ping="/$TBT_REWRITEURL$"   rel="/$TBT_URL$" class="breadcrumb_txt1">$TBT_LINKNAME$</a>
  
</span>
