<div class="col-sm-20 col-md-20  clearfix">
  <div class="ctgry-headpanel clearfix">
    <div class="categoryheading nolftpadd">
      <img src="$CDN$Images/downarrow_B.png" alt="" height="15" width="15"/>
    </div>
    <div class="categoryheading nolftpadd">
      <h4>Site Map</h4>
    </div>
    <div class="categoryheading nolftpadd">
      <a href="AutoSitemap.aspx" id="AutoSitemapxml" >
        <img src="$CDN$Images/xml-icon.jpg" title="View XML Sitemap" style="height:52px;" />
      </a>
    </div>
    <div class="sort-btns">
      <img src="$CDN$Images/ico_8.png" width="83" height="71" alt=""/>
    </div>
  </div>



 $TBWDataList:{$it.TBWDataListItem$}$



</div>


        



  
 

 











  