<!--<div class="ctgry-headpanel clearfix">
  <div class="categoryheading">
    <h4>Terms &amp; Conditions</h4>
    <p>Find out more about Wagner. If you can't find the information you need, please use the Make an Enquiry page or phone 1100 13 933 and get help from a Customer Service representative.</p>
  </div>
  <div class="categoryheading">
    <strong>GENERAL INFORMATION AND CONDITIONS</strong>
    <p>Find out more about Wagner. If you can't find the information you need, please use the Make an Enquiry page or phone 1100 13 933 and get help from a Customer Service representative.</p>
  </div>
  <div>
    <p>
      <strong>WAGNER ELECTRONICS:</strong>  Wagner Electronics is an Independent Australian Company dedicated to the Electronics Industry. Our aim is to give you the Best possible service at Competitive Prices.
    </p>

    <p>
      <strong>THE PRODUCTS</strong>:  Goods supplied are sourced from numerous sources locally and overseas.  It is our policy to purchase from reputable suppliers in order to assure that the products are of the highest quality.
    </p>
    <p>
      <strong>PRICES:</strong>  The prices shown are current at the time of display however there are many factors which can effect cost prices including material cost rises, shortages and currency variations, etc. The intention is to maintain the published prices however this may not be possible in all cases.
      Prices are therefore subject to change without notice.
    </p>
    <p>
      <strong>OWNERSHIP OF GOODS</strong>:  Goods and Services supplied by Wagner Electronics remain the property of Wagner Electronics, in accordance with the retention of title clause, until goods supplied are paid for by the customer.
    </p>
    <p>
      <strong>LIABILITY</strong>:  The use of the products purchased is beyond our control or supervision. We therefore cannot accept any liability for losses or consequential damage to any goods or equipment. Although WES does not manufacture the goods sold, we do ensure that the products are of the highest quality however in a rare event of a product being faulty, we will make a claim to our supplier on your behalf.  Each supplier have their own policy on returned goods which range from repair to replacement after inspection.
    </p>
    <p>
      <strong>DANGEROUS GOODS</strong>:  Orders with goods which are restricted, such as some batteries, aerosols or isopropanol products must be sent by road.
    </p>
    <p>
      <strong>BACK ORDERS</strong>:  Goods not in stock will be automatically back ordered and shipped when available with your next order unless otherwise requested..
    </p>
    <p>
      <strong>GOODS RETURNED</strong>:  Please, it is essential you obtain a Return Authorisation number ( RA ) before returning any goods. All goods to be returned must be freight prepaid and accompanied with a copy of the original purchase invoice. The RA number must be clearly written on the parcel. Parcels returned without an RA will not be accepted or will be returned. Faulty goods will be returned to our supplier for their determination. Faulty goods will be replaced or repaired only, not credited. Goods purchased incorrectly or no longer required are not able to be returned. For goods that are returned, they must be sent back in the original packaging and same as new condition they were received in; that is no price tags, shipping labels, tape / text marks, physical damage to box, etc. Please ensure that all items are returned including any parts, accessories and instructions that were included with the original product.
    </p>
    <p>
      <strong>ERRORS / OMISSIONS</strong>:  Due to the extensive product range, it is possible that mistakes exist. All care has been taken to eliminate errors, but no responsibility can be accepted. Please tell us if you discover any discrepancies.
    </p>
    <p>
      <strong>AUSTRALIA WIDE DELIVERY *</strong>:  Australia wide flat rate delivery charge of &#36;12.95*<br />*Additional charges may occur for Heavy / Large items (such as Server Racks) and non-standard delivery areas within Australia. Our sales team will notify you if there any additional chargers.
    </p>
    <p>
      <strong>PICK UPS</strong>:  Goods can be picked up from our premises from 8.30AM to 5.00PM Monday to Friday and from 9AM till 4PM on Saturday.
      In order to avoid delays it is recommended that you place your order 2 hours prior to pick up.<br />
      If you are picking up on Saturday please place your order on Friday.<br />
      Important Details For Store Pick Up:<br />
      1. Please bring a printed copy of invoice when coming into store.<br />
      2. Proof of Identity is required when picking up goods from our store. Please ensure you have the Credit Card you made the purchase with and your Driver License ID.<br />
      3. The Name on the Credit Card Must Match Your Driver's License ID.<br />
      4. You will not be able to pick up the goods from our store unless the Credit Card you made the purchase with and your Driver's License are shown OR if there if there is a mismatch between the in the name / details on your credit card and drivers licence details.
    </p>
    <p>
      <strong>INTERNATIONAL SHIPPING</strong>:  We ship internationally, once your order is submitted to us we will advise shipping cost by email and update your update order with freight cost.
    </p>
    
    
  </div>
</div>-->


<div class="privacypolicy">
  <h2>Terms &amp; Conditions</h2>
  Find out more about Wagner. If you can't find the information you need, please use the Make an Enquiry page or phone 1100 13 933 and get help from a Customer Service representative.
  <br />
    <br />

      <div class="centered-block">
        <h3 class="bld_fnt blue_text">GENERAL INFORMATION AND CONDITIONS </h3>
      </div>

      <h3>WAGNER ELECTRONICS:</h3> Wagner Electronics is an Independent Australian Company dedicated to the Electronics Industry. Our aim is to give you the Best possible service at Competitive Prices.

      <h3>THE PRODUCTS:</h3> Goods supplied are sourced from numerous sources locally and overseas. It is our policy to purchase from reputable suppliers in order to assure that the products are of the highest quality.

      <h3>PRICES:</h3> The prices shown are current at the time of display however there are many factors which can effect cost prices including material cost rises, shortages and currency variations, etc. The intention is to maintain the published prices however this may not be possible in all cases. Prices are therefore subject to change without notice.

      <h3>OWNERSHIP OF GOODS:</h3> Goods and Services supplied by Wagner Electronics remain the property of Wagner Electronics, in accordance with the retention of title clause, until goods supplied are paid for by the customer.

      <h3>LIABILITY:</h3> The use of the products purchased is beyond our control or supervision. We therefore cannot accept any liability for losses or consequential damage to any goods or equipment. Although WES does not manufacture the goods sold, we do ensure that the products are of the highest quality however in a rare event of a product being faulty, we will make a claim to our supplier on your behalf. Each supplier have their own policy on returned goods which range from repair to replacement after inspection.

      <h3>DANGEROUS GOODS:</h3> Orders with goods which are restricted, such as some batteries, aerosols or isopropanol products must be sent by road.

      <h3>BACK ORDERS:</h3> Goods not in stock will be automatically back ordered and shipped when available with your next order unless otherwise requested..

      <h3>GOODS RETURNED:</h3> Please, it is essential you obtain a Return Authorisation number ( RA ) before returning any goods. All goods to be returned must be freight prepaid and accompanied with a copy of the original purchase invoice. The RA number must be clearly written on the parcel. Parcels returned without an RA will not be accepted or will be returned. Faulty goods will be returned to our supplier for their determination. Faulty goods will be replaced or repaired only, not credited. Goods purchased incorrectly or no longer required are not able to be returned. For goods that are returned, they must be sent back in the original packaging and same as new condition they were received in; that is no price tags, shipping labels, tape / text marks, physical damage to box, etc. Please ensure that all items are returned including any parts, accessories and instructions that were included with the original product.

      <h3>ERRORS / OMISSIONS:</h3> Due to the extensive product range, it is possible that mistakes exist. All care has been taken to eliminate errors, but no responsibility can be accepted. Please tell us if you discover any discrepancies.

      <h3>AUSTRALIA WIDE DELIVERY *:</h3> Australia wide flat rate delivery charge of &#36;9.90*
      *Additional charges may occur for Heavy / Large items (such as Server Racks) and non-standard delivery areas within Australia. Our sales team will notify you if there any additional chargers.

      <h3>PICK UPS:</h3> Goods can be picked up from our premises from 8.30AM to 5.00PM Monday to Friday and from 9AM till 4PM on Saturday. In order to avoid delays it is recommended that you place your order 2 hours prior to pick up.
      If you are picking up on Saturday please place your order on Friday.
      Important Details For Store Pick Up:
      <li>1. Please bring a printed copy of invoice when coming into store.</li>
      <li>2. Proof of Identity is required when picking up goods from our store. Please ensure you have the Credit Card you made the purchase with and your Driver License ID.</li>
      <li>3. The Name on the Credit Card Must Match Your Driver's License ID.</li>
      <li>4. You will not be able to pick up the goods from our store unless the Credit Card you made the purchase with and your Driver's License are shown OR if there if there is a mismatch between the in the name / details on your credit card and drivers licence details.</li>

      <h3>INTERNATIONAL SHIPPING:</h3> We ship internationally, once your order is submitted to us we will advise shipping cost by email and update your update order with freight cost.
      <br />
        <br />



            
</div>









