<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Account Sign Up Activation Details</title>

</head>
<body style="font-family:Arial, Helvetica, sans-serif;">

<table width="650"  cellpadding="0" cellspacing="0" border="0" style="border:solid thin #ddd;">

  <tr>
   <td width="50%" style="text-align:center;color:#fff; font-size:16px;"  >
<img src="https://www.wagneronline.com.au/images/mail_header_wagner.png" alt="wagner-logo"/>
</td>
    <td></td>
    <td >
<img src="https://www.wagneronline.com.au/images/mail_header.gif" alt="logo"/>
</td>
  </tr>
  <tr style="background:#3AB54A;height:50px;text-align:center;">
    <td colspan="3"><strong style="color:#fff;font-size:16px;"><i>Wagner Online Password Reset</i></strong></td>
  </tr>
  
  <tr style="background:#f1f1f1;height:50px;text-align:center;">
    <td colspan="3"><strong style="color:#8f8f8f;font-size:16px;"><i>Dear Customer</i></strong></td>
  </tr>
  <tr>
    <td colspan="3" style="padding:10px;line-height:24px;font-size:15px;" >Please follow the link below and complete details on the password reset page to change your password. </td>
  </tr>
 <tr>
    <td colspan="3" style="padding:10px;line-height:24px;font-size:15px;" > <a href="$URL$">$URL$ </a></td>
  </tr>

  <tr>
  <td colspan="3" style="padding:10px;line-height:24px;font-size:15px;">
<div style="visibility:hidden !important;display:none !important">
  <table width="650" border="0" class="sec_Tab">
  <tr>
    <td colspan="3" style="height:50px; text-align:center; background:#3AB54A; color:#fff; font-size:15px;"  cellpadding="0" cellspacing="0"><strong>Your Details</strong></td>
  </tr>
 
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" ></td>
  </tr>
  <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" ></td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" ></td>
  </tr>
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" ></td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" ></td>
  </tr>
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" ></td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" ></td>
  </tr>
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" ></td>
    <td colspan="2" style="padding:10px;" > </td>
  </tr>
</table>
</div>


  </td>
  </tr>
  <tr>
  <td colspan="3" style="padding:10px;" >
  Best Regards,<br />
WAGNER Team</td>
  </tr>
  <tr>
    <td style="font-size:15px; height:50px; background:#c5c5c5;" colspan="3"><strong>
<span style="padding-left:15px; padding-right:10px;"><a href="sales@wagneronline.com.au" class="blue_text">Email: sales@wagneronline.com.au</a></span>
  <span style="padding-left:15px; padding-right:10px;">  Phone : (+61) 02-9798-9233</span>
  <span style="padding-left:15px; padding-right:10px;">  Fax : (+61) 02-9798-0017</span></strong></td>
  </tr>
  
</table>


</body>
</html>