<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Wagner-Form-BulkBuy-Enquiry</title>
<style>
body{ font-family:Arial, Helvetica, sans-serif; }
.blue_bg{ background:#3AB54A;}
.blue_text{color:#0069b3;}
.white_color{ color:#fff; font-size:20px;}
.text_center{ text-align:center;}
.bg_f1{ background:#f1f1f1;}
.height_50{ height:50px;}
.border_temp{ border:solid thin #ddd;}
.padding_10{ padding:10px;}
.header_col_text{ color:#8f8f8f;}
.con_bg{ background::#f4f4f4;}
.line_height24{ line-height:24px;}
.font_size15{ font-size:15px;}
.padding_left_right{ padding-left:15px; padding-right:10px;}
.height_30{ height:50px;}
.font_weight{ font-weight:bold;}
.sec_Tab{   border: 1px solid #ddd; margin-bottom:10px;}
.green_bg{ background:#E9E9E9;}
.font_16{ font-size:16px;}
.foot{ background:#c5c5c5;}
</style>
</head>

<body style="font-family:Arial, Helvetica, sans-serif; ">
<table width="650" height="" cellpadding="0" cellspacing="0" border="0" style="border:solid thin #ddd;">
<tr>
    <td width="50%" style="text-align:center;color:#fff; font-size:16px;"><img src="https://www.wagneronline.com.au/images/micrositeimages/micrositeimages/mail_header_wagner.png"></td>
    <td></td>
    <td style="background:#fff;">
	<strong><img src="https://www.wagneronline.com.au/images/micrositeimages/mail_header.gif" alt="mail-logo"/></strong>
	</td>
  </tr>
  <tr style="background:#3AB54A;height:50px;text-align:center;">
    <td colspan="3"><strong style="color:#fff;font-size: 16px;"><i>Wagner Form BulkBuy Enquiry</i></strong></td>
  </tr>
  
  <tr>
  <td colspan="3">
  <table width="650" border="0" style="border: 1px solid #ddd; margin-bottom:10px;">
  <tr>
   <td cellspacing="0" cellpadding="0" style="height:50px; text-align:center; background:#F1F1F1; font-size:15px; color:#8f8f8f;" colspan="3"><strong><em>Your Details</em></strong></td>
  </tr>
  <tr style="background:#f1f1f1; font-size:15px;">
    <td width="40%" style="padding:10px;">ProductCode</td>
    <td colspan="2" style="padding:10px;">$PRODUCT_CODE$</td>
  </tr>
  <tr style="font-size:15px">
    <td style="padding:10px;">Product Link</td>
    <td colspan="2" style="padding:10px;"><a style="color:#15c;" href="$URL$">$URL$</a> </td>
  </tr>
  <tr style="font-size:15px; background:#f1f1f1;">
    <td style="padding:10px;">Full Name </td>
    <td colspan="2" style="padding:10px;">$FIRSTNAME$</td>
  </tr>
  <tr style="font-size:15px">
    <td style="padding:10px;">QTY </td>
    <td colspan="2" style="padding:10px;">$QTY$</td>
  </tr>
   <tr style="font-size:15px; background:#f1f1f1;">
    <td style="padding:10px;">Email id </td>
    <td colspan="2" style="padding:10px;">		<a style="color:#15c;" href="mailto:$EMAILID$">$EMAILID$</a></td>
  </tr>
  <tr style="font-size:15px">
    <td style="padding:10px;">Delivery Time</td>
    <td colspan="2" style="padding:10px;">$DELIVERYTIME$</td>
  </tr>
   <tr style="font-size:15px; background:#f1f1f1;">
    <td style="padding:10px;">Phone </td>
    <td colspan="2" style="padding:10px;">$PHONE$</td>
  </tr>
  <tr style="font-size:15px">
    <td style="padding:10px;">Target Price</td>
    <td colspan="2" style="padding:10px;">$TARGETPRICE$</td>
  </tr>
   <tr style="font-size:15px; background:#f1f1f1;">
    <td style="padding:10px;">Notes / Addtional Info</td>
    <td colspan="2" style="padding:10px;">$NOTES$</td>
  </tr>
  <tr style="font-size:15px">
    <td style="padding:10px;">Customer Type</td>
    <td colspan="2" style="padding:10px;">$CUSTOMER_TYPE$</td>
  </tr>
  
</table>



  </td>
  </tr>
  <tr>
  <td colspan="3" style="padding:10px;">
  Thanks & Regards,<br />
$FIRSTNAME$
</td>
  </tr>
 <tr>
    <td style="font-size:15px; height:50px; background:#c5c5c5;" colspan="3"><strong>
<span style="padding-left:15px; padding-right:10px;"><a href="" style="color:#0069b3;">Email: sales@wagneronline.com.au</a></span>
  <span style="padding-left:15px; padding-right:10px;">  Phone : (+61) 02-9798-9233</span>
  <span style="padding-left:15px; padding-right:10px;">  Fax : (+61) 02-9798-0017</span></strong></td>
  </tr>
  
</table>


</body>
</html>
