<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Account Sign Up Activation Details</title>
</head>
<body style="font-family:Arial, Helvetica, sans-serif;">
<table width="650" height="" cellpadding="0" cellspacing="0" border="0" style="border:solid thin #ddd;">
  <tr>
   <td width="50%" style="text-align:center;color:#fff; font-size:16px;"  ><strong><img src="https://www.wagneronline.com.au/images/mail_header_wagner.png" /></strong></td>
    <td></td>
    <td ><img src="https://www.wagneronline.com.au/images/mail_header.gif" /></td>
  </tr>
  <tr style="background:#3AB54A;height:50px;text-align:center;">
    <td colspan="3"><strong style="color:#fff;"><i>Activation Link</i></strong></td>
  </tr>
  
  <tr style="background:#f1f1f1; height:50px; text-align:center">
    <td colspan="3"><strong style="color:#8f8f8f;"><i>Dear Customer</i></strong></td>
  </tr>
  <tr>
    <td colspan="3" style="padding:10px;line-height:24px;font-size:15px;">To get started shopping please confirm your registration by clicking on the activation link below</td>
  </tr>
  
  <tr>
    <td colspan="3" style="padding:10px;line-height:24px;font-size:15px;"> 
	<a href="$Reactivation$" style="color:#15c;">
	$Reactivation$ </a></td>
  </tr>
  
  
  <tr>
  <td colspan="3">
<div style="visibility:hidden !important;display:none !important">
  <table width="650" border="0" class="sec_Tab">
  <tr>
    <td colspan="3" style="height:50px; text-align:center; background:#3AB54A; color:#fff; font-size:15px;"  cellpadding="0" cellspacing="0"><strong>Your Details</strong></td>
  </tr>
       $if(TBT_Bussiness)$
  <tr style="background:#f1f1f1; font-size:15px;">
    <td width="40%" style="padding:10px;" >Company Name</td>
    <td colspan="2" style="padding:10px;" >$CompanyName$</td>
  </tr>
  <tr style=" font-size:15px;" >
    <td style="padding:10px;" >ABN No</td>
    <td colspan="2" style="padding:10px;" >$ABNNo$</td>
  </tr>
  $endif$
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" >First Name</td>
    <td colspan="2" style="padding:10px;" >$FirstName$</td>
  </tr>
  <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" >Last Name</td>
    <td colspan="2" style="padding:10px;" >$LastName$</td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" >Phone</td>
    <td colspan="2" style="padding:10px;" >	$PhoneNo$</td>
  </tr>
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" >Mobile/Cell Phone</td>
    <td colspan="2" style="padding:10px;" >	$MobileNo$</td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" >Fax</td>
    <td colspan="2" style="padding:10px;" >	$Fax$</td>
  </tr>
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" >Email</td>
    <td colspan="2" style="padding:10px;" >	$Email$</td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" >Street Address</td>
    <td colspan="2" style="padding:10px;" >$Address1$</td>
  </tr>
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" >Address Line2</td>
    <td colspan="2" style="padding:10px;" >$Address2$ </td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" >Suburp/Town</td>
    <td colspan="2" style="padding:10px;" >$Town$</td>
  </tr>
  <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" >State/Province</td>
    <td colspan="2" style="padding:10px;" >$state$</td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" >Postcode/ZipCode	</td>
    <td colspan="2" style="padding:10px;" >$zip$</td>
  </tr>
   <tr style="background:#f1f1f1; font-size:15px;">
    <td style="padding:10px;" >Country</td>
    <td colspan="2" style="padding:10px;" >$country$</td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" >Password</td>
    <td colspan="2" style="padding:10px;" >	$password$</td>
  </tr>
  <tr style=" font-size:15px;">
    <td style="padding:10px;" >LOGIN NAME</td>
    <td colspan="2" style="padding:10px;" >	$loginname$ </td>
  </tr>
</table>
</div>


  </td>
  </tr>
  <tr>
  <td colspan="3" style="padding:10px;" >
  Best Regards,<br />
WAGNER Team</td>
  </tr>
  <tr>
    <td style="font-size:15px; height:50px; background:#c5c5c5;" colspan="3"><strong>
<span style="padding-left:15px; padding-right:10px;"><a href="sales@wagneronline.com.au" class="blue_text">Email: sales@wagneronline.com.au</a></span>
  <span style="padding-left:15px; padding-right:10px;">  Phone : (+61) 02-9798-9233</span>
  <span style="padding-left:15px; padding-right:10px;">  Fax : (+61) 02-9798-0017</span></strong></td>
  </tr>
  
</table>


</body>
</html>