<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>USB Flash Drives</title>
<style type="text/css">
{
				border-width: 0px;
}
</style>
<base target="_blank" />
</head>
<body bgcolor="#eeeeee" style="margin-top: 0;margin-bottom: 0; margin-left:0; margin-right:0; padding-top: 0;padding-bottom: 0;-webkit-text-size-adjust: 100%;-ms-text-size-adjust: 100%;-webkit-font-smoothing: antialiased;width: 100%; font-family: 'Lucida Grande', 'Lucida Sans Unicode', 'Lucida Sans', Tahoma, Helvetica, Arial, Verdana, sans-serif;">
<!-- START OVERALL WRAPPER TABLE -->
<table align="center" width="550px" cellpadding="0" cellspacing="0" border="0" >
<tbody>
<tr>
  <td style="margin-top: 0;margin-bottom: 0;padding-top: 0;color: #555555;border-collapse: collapse;padding-left: 0;padding-right: 0;margin-left: 0;margin-right: 0;" bgcolor="#eeeeee"><!-- ******* START HEADER 1 MODULE ******* -->
    
    <!-- START BROWSER VIEW MODULE -->
    </td>
    </tr></tbody></table>
    <!-- END BROWSER VIEW MODULE -->
    <!-- START 600px WRAPPER -->
    <table align="center" cellpadding="0" cellspacing="0" border="0" style="width: 600px">
      <tbody>
      <tr>
        <td bgcolor="#ffffff" style="padding: 35px 0 0px 0; border-top: 1px solid #fcb4b4; border-bottom: 1px solid #fcb4b4; margin-top: 0; margin-bottom: 0; color: #555555; border-collapse: collapse; margin-left: 0; margin-right: 0; border-top-color: #0069B3; border-bottom-color: #0069B3;"><!-- HEADER MODULE -->
          <table align="center" cellpadding="0" cellspacing="0" border="0">
            <tbody>
              <tr>
                <td width="550" style="margin-top: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 20px;color: #555555;border-collapse: collapse;padding-left: 0;padding-right: 0;margin-left: 0;margin-right: 0;"><table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                      <tr>
                        <td width="550" style="margin-top: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;color: #555555;border-collapse: collapse;padding-left: 0;padding-right: 0;margin-left: 0;margin-right: 0;border: 0px solid #FFFFFF; vertical-align: middle; text-align: center;" class="style1">
						<a target="_blank" href="https://www.wagneronline.com.au/">
						<img alt="Wagner" src="https://www.wagneronline.com.au/mp/email/template/wagnerheader.gif" width="421" height="93" class="newStyle1" style="border-width: 0px; top: 10px;" /></a></td>
                      </tr>
                    </tbody>
                  </table></td>
              </tr>
            </tbody>
          </table>
          <!-- HEADER MODULE -->
          <!-- START CONTACT DETAILS -->
          <table align="center" cellpadding="0" cellspacing="0" border="0">
            <tbody>
              <tr>
                <td style="padding: 0 0 15px 0; margin: 0; color: #555555; border-collapse: collapse; width: 550px;"><table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                      <tr>
                        <td valign="bottom" style="margin: 0; padding: 0 10 0 10; color: #555555; width: 590px; border-collapse: collapse; font-family: Arial, Helvetica, sans-serif; font-size: 12px; vertical-align: top; text-align: center; line-height: 20px; height: 40px;"> Web: 
						<a style="color: #555555; text-decoration: none;" href="https://www.wagneronline.com.au">
						https://www.wagneronline.com.au</a><br />
												Email: 
						<a style="color: #555555; text-decoration: none;" href="mailto:sales@wagneronline.com.au">
						sales@wagneronline.com.au</a> | Phone: 02-9798-9233 </td>
                      </tr>
                    </tbody>
                  </table></td>
              </tr>
            </tbody>
          </table>
          <!-- END OF CONTACT DETAILS -->
          <!-- START TEXT-PHOTO-COMBO-02 MODULE -->
          <!-- END TEXT-PHOTO-COMBO-02 MODULE -->
                   
         
          
                    <!-- START DIVIDER-02 MODULE -->
          <table align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff">
            <tbody>
              <tr>
                <td width="550" height="1" style="margin-top: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;color: #555555;border-collapse: collapse;padding-left: 0;padding-right: 0;margin-left: 0;margin-right: 0;border-top: 3px dotted #cccccc;height: 1px;font-size: 1px;line-height: 0; border-top-style: dashed; border-top-width: 1px; border-top-color: #DDDDDD;">
				<img hspace="0" alt="spacer" vspace="0" src="https://www.wagneronline.com.au/mp/email/template/wnspacer.gif" width="1" height="1" style="border: 0;display: block;outline: none;"/></td>
              </tr>
            </tbody>
          </table>
          <!-- END DIVIDER-02 MODULE -->
                 <!-- START TEXT-PHOTO-COMBO-02 MODULE -->
          <table align="center" cellpadding="0" cellspacing="0" border="0">
            <tbody>
              <tr>
                <td width="550" style="margin: 0; padding: 20px 0 20px 0; color: #555555; border-collapse: collapse; height: 632px;">
                  <table cellpadding="0" cellspacing="0" border="0">
                    <tbody>
                      <tr>
                        <td width="550" align="left" style="margin: 0; padding-top: 0; padding-bottom: 0; color: #555555; border-collapse: collapse; padding-left: 25px; padding-right: 0; height: 144px;">
						<h1 style="font-size: 28px;letter-spacing: -1px;margin-bottom: 10px;font-weight: normal;font-family: 'Lucida Sans Unicode','Lucida Grande','Lucida Sans',Helvetica,Verdana,sans-serif;line-height: 100%;margin-top: 0;padding-top: 0;padding-bottom: 0;color: #CC0000;"> 
											<a target="_blank" style="color: #0069B3; text-decoration: none; font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; font-size: 22px; font-weight: bold;" href="https://www.wagneronline.com.au/">
											Welcome to WagnerOnline.com.au!</a></h1>
						
						            <p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 30px; margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 21px;color: #333333; letter-spacing: 0; font-weight: normal;">
							Dear $FirstLastName$ ,<br />
							<br />
							Welcome to wagneronline.com.au store. <br />
							<br />
							As a Wagner customer you will now be able 
							to:</p>
						<ul>
										<li>
										<p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 0px; margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 16px; color: #333333; letter-spacing: 0;">
										Quickly place orders online.</p>
										</li>
										<li>
										<p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 0px; margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 16px; color: #333333; letter-spacing: 0;">
										View and track your orders;</p>
										</li>
										<li>
										<p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 0;margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 16px; color: #333333; letter-spacing: 0;">
										Be the first to get our latest 
										specials and exclusives.</p>
										</li>
						</ul>
						<p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 25px; margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 21px;color: #333333; letter-spacing: 0;">
							To log in, please visit our site and click 
							on the 
							Login link that is located at the top of the 
							website, enter your e-mail address and password to 
							get started.</p>
						<p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 25px; margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 21px;color: #333333; letter-spacing: 0;">
							<a href="http://www.facebook.com/wagner.electronics" style="color: #0069B3; text-decoration: none">
							p.s Follow us on Facebook for the latest product 
							news and updates.</a><br />
							<br />
						<a href="http://www.facebook.com/wagner.electronics" target="_blank">
						<img alt="fb" src="https://www.wagneronline.com.au/mp/email/template/wgfb.gif" width="182" height="70" style="border-style: 0; border-color: 0; border-width: 0px;" /></a></p>
						<p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 25px; margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 21px;color: #333333; letter-spacing: 0;">
							Thanks,<br />
							The Team from Wagner Online</p>
						<p style="font-family: 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Helvetica, Verdana, sans-serif; margin-top: 0;margin-bottom: 15px;padding-top: 0;padding-bottom: 0;font-size: 14px;line-height: 21px;color: #777777;letter-spacing: 0;">
							<a target="_blank" href="https://www.wagneronline.com.au" style="color: #0069B3; text-decoration: none">
							www.wagneronline.com.au</a></p>
                          </td>
                      </tr>
                    </tbody>
                  </table>
				</td>
              </tr>
            </tbody>
          </table>
                  
          
          
                    <!-- START DIVIDER-02 MODULE -->
          <table align="center" cellpadding="0" cellspacing="0" border="0" bgcolor="#ffffff">
            <tbody>
              <tr>
                <td width="550" height="1" style="margin-top: 0;margin-bottom: 0;padding-top: 0;padding-bottom: 0;color: #555555;border-collapse: collapse;padding-left: 0;padding-right: 0;margin-left: 0;margin-right: 0;border-top: 1px dotted #cccccc;height: 1px;font-size: 1px;line-height: 0;">
				<img hspace="0" alt="spacer" vspace="0" src="https://www.wagneronline.com.au/mp/email/template/wnspacer.gif" width="1" height="1" style="border: 0;display: block;outline: none;"/></td>
              </tr>
            </tbody>
          </table>
          <!-- END DIVIDER-02 MODULE -->

                
                 
          <!-- START HIGHLIGHT-03 MODULE -->
          <table align="center" cellpadding="0" cellspacing="0" border="0">
            <tr>
              <td width="542" style="margin-top: 0;margin-bottom: 0;padding-top: 10px;padding-bottom: 20px;color: #555555;border-collapse: collapse;padding-left: 0;padding-right: 0;margin-left: 0;margin-right: 0; ">
				<table align="center" cellpadding="0" cellspacing="0" border="0" style="text-align: center;" class="style2">
                  <tr>
                    <td width="550" style="padding: 25px 0 25px 0; margin-top: 0; margin-bottom: 0; color: #555555; border-collapse: collapse; margin-left: 0; margin-right: 0; align: center; ">
                        <table align="center" cellpadding="0" cellspacing="0" border="0">
                          <tbody>
                            <tr>
                              <td valign="bottom" style="border-style: 0; border-width: 0px;">
                                <a target="_blank" href="https://www.wagneronline.com.au/new-products/909/ct/"> 
								<img alt="Latest Updates" src="https://www.wagneronline.com.au/mp/email/template/wnbtnwagner.gif" width="116" height="180" style="border-style: 0; border-width: 0px; padding: 0px; margin: 0px 5px;"/></a>
								<a target="_blank" href="https://www.wagneronline.com.au/ContactUs.aspx"> 
								<img alt="Contact Us" src="https://www.wagneronline.com.au/mp/email/template/wnbtncontactwagner.gif" width="116" height="180" style="border-style: 0; border-width: 0px; padding: 0px; margin: 0px 5px;"/></a>
								<a target="_blank" href="https://www.wagneronline.com.au/"> 
								<img alt="Online Store" src="https://www.wagneronline.com.au/mp/email/template/wnbtnorderwagner.gif" width="116" height="180" style="border-style: 0; border-width: 0px; padding: 0px; margin: 0px 5px;"/></a>
								<a target="_blank" href="https://www.wagneronline.com.au/catalogue/"> 
								<img alt="Browse Online Catalogue" src="https://www.wagneronline.com.au/mp/email/template/wnbtnebookwagner.gif" width="116" height="180" style="border-style: 0; border-width: 0px; padding: 0px; margin: 0px 5px;"/></a></td>
                            </tr>
                          </tbody>
                        </table>
                      </td>
                  </tr>
                </table>
                <!-- END HIGHLIGHT-03 MODULE -->
                <!-- END 600px WRAPPER --></td>
            </tr>
          </table>
          <!-- END HIGHLIGHT-03 MODULE -->
          <!-- ******* START FOOTER-01 MODULE ******* -->
          <!-- ******* END FOOTER-01 MODULE ******* --></td>
      </tr>
      </tbody>
    </table>
    <!-- END OVERALL WRAPPER TABLE -->
</body>
</html>