<h1>About Us</h1>



<p>



</p>

<p>
  <h3>&nbsp;</h3>

  <h3>
    <strong>What we do</strong>
  </h3>

  <p>High Fidelity sound should be able to be appreciated by all. LSK are an Australian business dedicated to providing excellent DIY speaker kits and great value audio components for stereo and home theatre enthusiasts. Typically, Hi-Fi products often command a ‘luxury’ price tag, but LSK bucks that trend by providing high quality solutions at a price anyone can afford.</p>

  <h3>&nbsp;</h3>

  <h3>
    <strong>Australia's DIY specialists</strong>
  </h3>

  <p>The original LSK, or “The Loudspeaker Kit” was designed and launched in the late 90s to great success. The first designs were the brainchild of a DIY enthusiast who knew that better sound could be achieved through clever component selection and design. By removing the assembly and finishing costs, and offering speakers in kit form to consumers, prices were kept low but sound quality was kept high.</p>

  <p>In 2012, ownership was transferred to Melbourne's SGR Corporation P/L, the parent company for a number of successful entities but most well known in the audio scene for its high-end design and manufacturing division known as SGR Audio.</p>

  <p>LSK now operates from dedicated facilities in Melbourne, where all speaker kits are designed and built in-house. LSK has extensive warehouse facilities, holds stock, and ships globally on a daily basis.</p>

  <p>&nbsp;</p>

  <h3>
    <strong>Design</strong>
  </h3>

  <p>LSK's original speaker kits were always a hit, but the current generation of kit's, launched in 2014, bring a whole new level of performance. Each kit has been re-vamped and overhauled by high-end loudspeaker designer, Stuart Graeme Ralston, Mr SGR himself! There's now a chance for everyone to own some SGR magic, at very affordable prices!</p>

  <p>Now under the SGR wing, all LSK products perform well above their price point. Customer service, advice and product support is now second to none.&nbsp;</p>

  <h3>&nbsp;</h3>

  <h3>
    <strong>The team</strong>
  </h3>

  <p>
    Stuart oversees the design and manufacture of the LSK kits, but does not get involved in the day to day operations of the business. LSK is managed by Daniel Hoskin, an avid audio enthusiast and musician. Technical support and advice is provided by Paul Spencer, a self-confessed uber blogger and long-time DIY advocate. You'll find a number of Paul's informative articles and posts on various audio forums, especially&nbsp;<a href="http://www.stereo.net.au/" target="_blank">www.stereo.net.au</a>.
  </p>

  <h3>&nbsp;</h3>

  <h3>
    <strong>The DIY alternative</strong>
  </h3>

  <p>It’s our passion to help people discover that DIY speakers give you the best bang for buck around. Our kits are designed to make DIY simple, even for beginners. LSK kits are supplied as flat packs that require gluing, assembly and finishing. In 2015 we will be introducing to option to buy some of the LSK speaker models in completed form, for those that aren't quite cut out for the DIY thing but still want to experience the quality sound that LSK products provide.</p>

  <h3>&nbsp;</h3>

  <h3>
    <strong>More than just kits</strong>
  </h3>

  <p>We offer far more than just DIY kits. We also sell a great range of acoustic treatment products, amplifiers and many other products ranging from drivers, parts, cables and spikes.</p>

  <p>We are the Australian distributors for Dayton Audio and resellers for many popular loudspeaker driver brands such as Scan Speak and SB Acoustics.</p>

  <h3>&nbsp;</h3>

  <h3>
    <strong>Proudly Australian Made</strong>
  </h3>

  <p>Our LSK branded speaker kits and acoustic treatment kits are proudly made here in Australia. We prefer to use Australian suppliers wherever possible. Not only do we prefer to support local industry, we also believe that Aussies do it better!</p>



</p>



