

    <h4 class="bolder" >
      <span class="gray_40">Welcome to</span>
      <span class="blue_color_text">ReelPlay TV Australia Online Micro Store</span>
    </h4>

<br />
   <span class="blue_color_text bolder">WHAT WE DO.</span>
<br />
<div class="" style="height:100%">
Reelplay provides the means to access many international HD Quality TV Channels 
distributed to you over the Internet with many more channels added frequently. 
Our Reelplay Media Player and an internet connection is all you will need to be 
able to watch all these channels on your Home TV. 
Reelplay Channels are available any time, you just need an internet connection.. That's it..
</div>
<div class="" style="height:100%">
No more expensive subscription, No more expensive Hardware. 
This means that you as a customer will get rid of messy installations, 
dishes and cables with No buffering & smooth streaming. Guaranteed .
</div>
<br />
 <span class="blue_color_text bolder">HOW WE BECAME SO FAMOUS.</span>
<br />
<div class="" style="height:100%">

Reelplay pioneered streaming for the TV, and we aspire to power every TV in the world. 
We developed a streaming platform that delivers a best-in-class user experience. At the heart 
of the Reelplay platform is our proprietary streaming system, which we built from the ground up. 
Reelplay is recognized for streaming innovation. This is demonstrated by our growing, passionate 
and highly engaged customer base who love Reelplay streaming devices because of our coveted content selection, 
ease of use, and value for money.
</div> 
<br />
 <div class="" style="height:100%">
In 2014, Reelplay streamed over 100 thousand hours of content, 
up 60% from the prior year, and ended the year with about 0.5 million monthly active accounts. 
We grow the reach and scale of our platform by distributing a product with ease of use and low cost to the end user.
</div> 
<br />
 <div class="" style="height:100%">
We generate revenue from selling Reelplay streaming players.
</div> 
<br />
 <div class="" style="height:100%">
We believe that all television will be streamed, and that all TVs and set-top-boxes 
will be powered by software-based operating systems that provide a dramatically better 
user experience than has existed historically for the TV. Like the computer and mobile markets, 
a similar dynamic is happening with the big screen TV where only a small number 
of highly competitive platforms will exist.
</div> 
  <div class="clear margin_top"></div>

