

    <h4 class="bolder" >
      <span class="gray_40">Welcome to</span>
      <span class="blue_color_text">Cypress Converters</span>
    </h4>



    <div class="col-lg-4 col-sm-4">
    
        <img class="border_3 responsive_img" src="$CDN$images/micrositeimages/CYP_Aboutus1.jpg"/>
 
    </div>

      <div class="col-lg-8">


        <p class="para_about">
          Cypress Converters Australia deliver market leading connectivity solutions that enhance the capability of Audio Visual products in any installation environment. CYP is a market leader in connectivity solutions for both systems integrators and professional AV installers throughout Australia, Europe and USA. The Cypress product range has over 350 tried and tested products that offer a standard of performance and reliability that cannot be matched.
        </p>
      </div>
      <div class="col-lg-8">
        <p class="para_about">At CYP we are continuously developing new products and solutions that drive innovation. Within AV distribution this requires an excellent market understanding and the very best R&D engineers. CYP have a continuous new product roadmap containing over 30 projects at any one time, this ensures that we can always provide our partners with innovative application of the very latest technology.</p>
      </div>
      <div class="clear"></div>
 
    <div class="col-lg-4 col-sm-4">
    
        <img class=" responsive_img" src="$CDN$images/micrositeimages/CYP_Aboutus2.jpg"/>
    
    </div>


      <div class="col-lg-8">
        <p class="para_about">We support distributors, systems integrators and installers throughout the world. From initial specification of projects through to industry leading after sales support and training, we provide our partners with complete confidence in the AV solutions they deliver. Behind this support is a dedicated team of product managers and engineers who all have the skills and experience to deliver practical help at every stage of the CYP journey. It is this passion for the industry and pride in our products that makes us the perfect manufacturer partner, we specialise in solutions for HDBaseT, Modular Matrix, AV Conversion, HDMI Distribution, Audio Converters and more.</p>
      </div>
      
      


      <div class="clear margin_top"></div>
   







 
 

