<!--<div class="mar5">
  <div class="mobilemenu visible-phone">
    <div class="">
      <a href="#nav-1" class="btn-menuico open">
        <img src="/images/MicroSiteimages/mobmenu.png">
      </a>
    </div>
  </div>
  <ul id="nav-1" class="sidemenu border-rad5">
    <div class="mobmenu-header visible-phone">
      <a href="">About</a>
      <a href="">My Account</a>
      <a href="">Wagner Online</a>
    </div>
    <div class="left-title gradleft visible-phone">
      <a href="">
        <img src="/images/MicroSiteimages/homewhite-16.png">&nbsp;&nbsp;&nbsp;Home
      </a>
    </div>
    <div class="left-title bgblue">Product Categories</div>
    <div id="accordian">
<ul>
  $TBWDataList:{$it.TBWDataListItem$}$
</ul>
    </div>
  </ul>
</div>-->


<div class="list-group font_14">
  <a class="list-group-item active font_size_16"> Product Categories </a>
   $TBWDataList:{$it.TBWDataListItem$}$

</div>