<div class="clear">
  <!--<h4 class="bolder blue_color_text font_size_16">Sub Family Title</h4>-->
  <div data-example-id="bordered-table" class="bs-example col-lg-12 padding_left_right_mob">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th width="100">
            <img class="lazy" data-original="$CDNROOT$prodimages$TBT_TFWEB_IMAGE1$" width="100px" max-height="100%" style="text-decoration:none; border:0;" alt="$TBT_FAMILY_NAME$"/>
          </th>
          <th colspan="5" valign="top"  class="table_bg" style="vertical-align:Top;">
            <strong class="blue_color_text font_size_16">$TBT_FAMILY_NAME$</strong>
            <br />
              <span class="font_normal">$TBT_SHORT_DESCRIPTION$</span>
              <p class="font_normal"> $TBT_SHORT_DESCRIPTION1$</p>
              <p class="font_normal">$TBT_SHORT_DESCRIPTION2$</p>
              <p class="font_normal"> $TBT_SHORT_DESCRIPTION3$</p>
              <p class="font_normal">$TBT_SHORT_DESCRIPTION4$</p>
              <p class="font_normal">$TBT_DESCRIPTIONS$</p>
            </th>
        </tr>
      </thead>

    </table>
  </div>
  <div class="clear"></div>
</div>

