<div class="product-wraplv">
  <div class="product-boxlv mar5">
    <div id="imgcontainerlv" style="display: table;text-align: center;">
      $if(TBT_SUB_FAMILY)$

      <a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" style="display:table-cell;vertical-align:middle;text-align:center;height:100px;width:100px;background: none repeat scroll 0 0 #FFFFFF;color: #099dd9;" class="">
        <!--<img  alt="" src="/prodimages$ATTRIBUTE_ID_747$">-->
        <img class="lazy"  data-original="$CDN$prodimages$ATTRIBUTE_ID_747$" alt="$FAMILY_NAME$"  style="max-width:100px;max-height:100px;color:#fff;font-size:1px;"/>
      </a>

      $else$

      <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" style="display:table-cell;vertical-align:middle;text-align:center;height:100px;width:100px;background: none repeat scroll 0 0 #FFFFFF;color: #099dd9;" class="">
        <!--<img    alt="" src="/prodimages$ATTRIBUTE_ID_747$">-->
        <img class="lazy"  data-original="$CDN$prodimages$ATTRIBUTE_ID_747$" alt="$ATTRIBUTE_ID_1$ $PROD_DESC_ALT$" style="max-width:100px;max-height:100px;color:#fff;font-size:1px;" />
      </a>

      $endif$


    </div>
    <div class="gal-prod-contentlv">
      <div class="gal-prod-title">
        $if(TBT_SUB_FAMILY)$

        <a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" style="text-decoration:none;color: #099dd9;">
          $FAMILY_NAME$
        </a>

        $else$

        <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" style="text-decoration:none;color: #099dd9;">$FAMILY_NAME$</a>

        $endif$


      </div>
      <div class="grid6  prod-item-desc">
        <div class="gal-prod-desc">

          <p style="margin:0px; margin-top:20px;">
            $ATTRIBUTE_ID_13$
            $if(TBT_MORE_13)$
            $if(TBT_SUB_FAMILY)$...
            <a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" class="tx_3">More Information</a>
            $else$...
            <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" class="tx_3">More Information</a>
            $endif$
            $endif$
          </p>
          <p>
            $ATTRIBUTE_ID_90$
            $if(TBT_MORE_90)$
            $if(TBT_SUB_FAMILY)$...
            <a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" class="tx_3">More Information</a>
            $else$...
            <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" class="tx_3">More Information</a>
            $endif$
            $endif$
          </p>
          <p>
            $ATTRIBUTE_ID_91$
            $if(TBT_MORE_91)$
            $if(TBT_SUB_FAMILY)$...
            <a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $else$...
            <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $endif$
            $endif$
          </p>
          <p>
            $ATTRIBUTE_ID_377$
            $if(TBT_MORE_377)$
            $if(TBT_SUB_FAMILY)$...<a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $else$...
            <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $endif$
            $endif$
          </p>
          <p>
            $ATTRIBUTE_ID_379$
            $if(TBT_MORE_379)$
            $if(TBT_SUB_FAMILY)$...<a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $else$...
            <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $endif$
            $endif$
          </p>
          <p>
            $ATTRIBUTE_ID_4$
            $if(TBT_MORE_4)$
            $if(TBT_SUB_FAMILY)$...
            <a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;ProductResult=SUCCESS&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$FAMILY_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $else$ ...
            <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;cid=$CATEGORY_ID$&amp;pcr=$PARENT_CATEGORY_ID$&amp;Path=$PRODUCT_EA_PATH$" style="color:#0099FF;text-decoration:none;">More Information</a>
            $endif$
            $endif$
          </p>

        </div>
      </div>
      <div class="cl"></div>
      <table width="100%" class="prod-opt">
        <tr>
          <td>
            $if(TBT_SUB_FAMILY)$
            <a class="hoverblack_m" href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?fid=$FAMILY_ID$&cid=$CATEGORY_ID$&ProductResult=SUCCESS&pcr=$PARENT_CATEGORY_ID$&Path=$FAMILY_EA_PATH$"  style="color: #099dd9;">
              <img src="$CDN$images/MicroSiteimages/searchblue.png" align="absmiddle">
                &nbsp;&nbsp;&nbsp;View $PRODUCT_COUNT$ of $FAMILY_PRODUCT_COUNT$ Product
            </a>
            $else$
            <a class="hoverblack_m" href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&fid=$FAMILY_ID$&cid=$CATEGORY_ID$&pcr=$PARENT_CATEGORY_ID$&Path=$PRODUCT_EA_PATH$"  style="color: #099dd9;">
              <img src="$CDN$images/MicroSiteimages/searchblue.png" align="absmiddle">
                &nbsp;&nbsp;&nbsp;View $PRODUCT_COUNT$ of $FAMILY_PRODUCT_COUNT$ Product
                
            </a>
            $endif$


          </td>
          <td>
            $if(TBT_SUB_FAMILY)$

            Order No: $ATTRIBUTE_ID_1$

            $else$
            <a class="hoverblack_m"  href="$TBT_REWRITEURL$/mpd/"  rel="/mpd.aspx?pid=$TBT_PRODUCT_ID$&fid=$FAMILY_ID$&cid=$CATEGORY_ID$&pcr=$PARENT_CATEGORY_ID$&Path=$PRODUCT_EA_PATH$" style="text-decoration:none;font-weight:normal;color: #099dd9;">
              <strong>  Order No: $ATTRIBUTE_ID_1$ </strong>
            </a>
            $endif$
          </td>
        </tr>
      </table>
    </div>
    <div class="grid3 mgntp">
      <div>
        $if(TBT_BUY_PRODUCT)$

        <table cellspacing="10" cellpadding="10" width="100%" style="max-width:190px; float:right;">
          <tbody>
            <tr>
              <td width="70%" align="right">
                <table width="100%">
                  <tr>
                    <td align="right">
                      $if(TBT_ECOMENABLED)$
                      <input name="txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$"   style="height: 30px;margin-top: -9px;width: 30px;padding:2px 0px;text-align: center;" size="2" maxlength="6" type="text" onkeydown="return keyct(event)" id="txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$" value="1" onkeyup="callproductqtykeypress(event)" />
                      $endif$
                      <span class="blue prod-item-tbl1-price">&nbsp;&nbsp;&#36;$TBT_USER_PRICE$</span>
                      <!--<span class="blue prod-item-tbl1-price">&nbsp;&nbsp;&nbsp;&#36;$TBT_USER_PRICE$</span>-->
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td align="right">
                $if(TBT_ECOMENABLED)$
                <!--<input name="txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$"   style="height: 24px;margin-left: 20px;width: 40px;float: left;" size="2" maxlength="6" type="text" onkeydown="return keyct(event)" id="txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$"/>-->
                <div class="costable" style="height:40px;margin-left:73px;">
                  <div class="pricepopup">
                    <div class="popupouterdiv1">
                      <div class="popupaero"></div>$TBT_PRODUCT_PRICE_TABLE$
                    </div>

                    <input type="button" name="" value="Add to Cart" style="cursor: pointer;" class="editbtn nw" onClick="productbuy('txt$TBT_PRODUCT_ID$_$TBT_QTY_AVAIL$_$TBT_MIN_ORD_QTY$_$TBT_FAMILY_ID$','$TBT_PRODUCT_ID$');">     
                      
                  </div>
                </div>
                $else$
                $if(TBT_SUB_FAMILY)$
                <a  href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?pid=$PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;byp=$BYP$&amp;cid=$CATEGORY_ID$&amp;path=$FAMILY_EA_PATH$" >
                  <img src="$CDN$images/MicroSiteimages/btn-more-info.png"> </a>
                $else$
                <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;byp=$BYP$&amp;cid=$CATEGORY_ID$&amp;path=$PRODUCT_EA_PATH$" >
                  <img src="$CDN$images/MicroSiteimages/btn-more-info.png" alt="" />   </a>
                $endif$
                $endif$
              </td>
            </tr>
          </tbody>
        </table>
        $else$
        <table width="100%" cellspacing="10" cellpadding="10" style="max-width:190px; float:right;">
          <tbody>
            <tr>
              <td width="70%" align="right">
                <strong>
                  Starting From:
                </strong>$TBT_MIN_PRICE$
              </td>
            </tr>

            <tr>
              <td align="right">

                $if(TBT_SUB_FAMILY)$
                <a href="$TBT_REWRITEURL$/mfl/" rel="/mfl.aspx?pid=$PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;byp=$BYP$&amp;cid=$CATEGORY_ID$&amp;path=$FAMILY_EA_PATH$" >
                  <img src="$CDN$images/MicroSiteimages/btn-more-info.png" alt=""/> 
                </a>
                $else$
                <a href="$TBT_REWRITEURL$/mpd/" rel="/mpd.aspx?pid=$PRODUCT_ID$&amp;fid=$FAMILY_ID$&amp;byp=$BYP$&amp;cid=$CATEGORY_ID$&amp;path=$PRODUCT_EA_PATH$"  >
                  <img src="$CDN$images/MicroSiteimages/btn-more-info.png" alt=""/>  </a>
                $endif$

              </td>
            </tr>
          </tbody>
        </table>
        $endif$

      </div>
      <div class="prod-item-tbl3"></div>
    </div>

    <div class="cl"></div>
  </div>
</div>

