<li>
  <!--<input type="submit" class="sidebar_button" id="$TBW_ATTRIBUTE_NAME$$TBW_OPTION_CATEGORY_ID$" value="$TBW_ATTRIBUTE_NAME$" onclick="OnclickTab('txt$TBW_ATTRIBUTE_INPUT$');">
  </input>
  <input type="hidden" id="txt$TBW_ATTRIBUTE_INPUT$"  value="$ORG_EA_PATH$@@$TBW_ATTRIBUTE_TYPE$@@$TBW_ATTRIBUTE_NAME_NEW$" />-->
  <a onclick="getValue_breadcrumb(this);" class="sidebar_button" style="cursor:default" ping="$TBT_REWRITEURL$" rel="$TBW_FORMNAME$&amp;id=0&amp;pcr=$TBW_PARENT_CATEGORY_ID$&amp;cid=$TBW_CATEGORY_ID$&amp;tsb=$TBW_BRAND$&amp;tsm=$TBW_MODEL$&amp;searchstr=$TBW_ATTRIBUTE_SEARCH$&amp;type=$TBW_ATTRIBUTE_TYPE$&amp;value=$TBW_ATTRIBUTE_VALUE$&amp;bname=$TBW_ATTRIBUTE_BRAND$&amp;byp=$TBW_CUSTOM_NUM_FIELD3$&amp;Path=$EA_PATH$">
      $TBW_ATTRIBUTE_NAME$ 
    </a>
</li>