<div class="maindiv">
  <section>
    <div class="contrant">
      <div class="grid12 hidden-phone">
        <div class="mar5 bgblue tit-header border-rad5 ">
          <div class="grid6">
            <div class="mar5">
              <a class="pg-homeico" href="">
                <img src="$CDN$images/homewhite-16.png"/>
              </a>
              <a class="nav2-link fleft" href="/vip-vision/919/mct/">Conceptronic Store - Wagner Online</a>
            </div>
          </div>
          <div class="grid6">
            <div class="mar5">
              <a class="nav2-link fright" href="">About us</a>
              <a class="nav2-link fright" href="">Downloads</a>
            </div>
          </div>
        </div>
      </div>
      <div class="grid3">
        <div class="mar5">
          <div class="mobilemenu visible-phone">
            <div class="">
              <a href="#nav-1" class="btn-menuico open">
                <img src="$CDN$images/mobmenu.png" />
              </a>
            </div>
          </div>
          <ul id="nav-1" class="sidemenu border-rad5">
            <div class="mobmenu-header visible-phone">
              <a href="">About</a>
              <a href="">My Account</a>
              <a href="">Wagner Online</a>
            </div>
            <div class="left-title gradleft visible-phone">
              <a href="">
                <img src="$CDN$images/homewhite-16.png" />&nbsp;&nbsp;&nbsp;Home
              </a>
            </div>
            <div class="left-title bgblue">Product Categories</div>
            <div id="accordian">
              <ul>
                <li>
                  <h3 onclick="func_showChild(1)" class="h3_1">
                    <span></span>Electronic Cigarette
                  </h3>
                  <ul>
                    <li>
                      <a href="">Home Audio &amp; Video</a>
                    </li>
                    <li>
                      <a href="">Electronic Publishing</a>
                    </li>
                    <li>
                      <a href="">Telecommunications</a>
                    </li>
                    <li>
                      <a href="">MP3/4 Accessories</a>
                    </li>
                  </ul>
                </li>
                <!-- we will keep this LI open by default -->
                <li>
                  <h3 onclick="func_showChild(2)" class="h3_2">
                    <span></span>Headphones &amp; Earphones
                  </h3>
                  <ul>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <h3 onclick="func_showChild(3)" class="h3_3">
                    <span></span>Batteries &amp; Charger
                  </h3>
                  <ul>
                    <li>
                      <a href="">Electronic Cigarette</a>
                    </li>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                    <li>
                      <a href="">Gadgets</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <h3 onclick="func_showChild(4)" class="h3_4">
                    <span></span>Home Audio &amp; Video
                  </h3>
                  <ul>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                    <li>
                      <a href="">Gadgets</a>
                    </li>
                    <li>
                      <a href="">Satellite &amp; Cable TV</a>
                    </li>
                    <li>
                      <a href="">Home Audio &amp; Video</a>
                    </li>
                    <li>
                      <a href="">Electronic Publishing</a>
                    </li>
                    <li>
                      <a href="">Telecommunications</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                    <li>
                      <a href="">Gadgets</a>
                    </li>
                    <li>
                      <a href="">Satellite &amp; Cable TV</a>
                    </li>
                    <li>
                      <a href="">Home Audio &amp; Video</a>
                    </li>
                    <li>
                      <a href="">Electronic Publishing</a>
                    </li>
                    <li>
                      <a href="">Telecommunications</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <h3 onclick="func_showChild(5)" class="h3_5">
                    <span></span>Headphones &amp; Earphones
                  </h3>
                  <ul>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <h3 onclick="func_showChild(6)" class="h3_6">
                    <span></span>Batteries &amp; Charger
                  </h3>
                  <ul>
                    <li>
                      <a href="">Electronic Cigarette</a>
                    </li>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                    <li>
                      <a href="">Gadgets</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <h3 onclick="func_showChild(7)" class="h3_7">
                    <span></span>Home Audio &amp; Video
                  </h3>
                  <ul>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                    <li>
                      <a href="">Gadgets</a>
                    </li>
                    <li>
                      <a href="">Satellite &amp; Cable TV</a>
                    </li>
                    <li>
                      <a href="">Home Audio &amp; Video</a>
                    </li>
                    <li>
                      <a href="">Electronic Publishing</a>
                    </li>
                    <li>
                      <a href="">Telecommunications</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                    <li>
                      <a href="">Gadgets</a>
                    </li>
                    <li>
                      <a href="">Satellite &amp; Cable TV</a>
                    </li>
                    <li>
                      <a href="">Home Audio &amp; Video</a>
                    </li>
                    <li>
                      <a href="">Electronic Publishing</a>
                    </li>
                    <li>
                      <a href="">Telecommunications</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <h3 onclick="func_showChild(8)" class="h3_8">
                    <span></span>Headphones &amp; Earphones
                  </h3>
                  <ul>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <h3 onclick="func_showChild(9)" class="h3_9">
                    <span></span>Batteries &amp; Charger
                  </h3>
                  <ul>
                    <li>
                      <a href="">Electronic Cigarette</a>
                    </li>
                    <li>
                      <a href="">Headphones &amp; Earphones</a>
                    </li>
                    <li>
                      <a href="">A/V Accessories &amp; Cable</a>
                    </li>
                    <li>
                      <a href="">Batteries &amp; Charger</a>
                    </li>
                    <li>
                      <a href="">MP3 Players</a>
                    </li>
                    <li>
                      <a href="">Gadgets</a>
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
          </ul>
        </div>
        <div class="mar5 mar-top20">
          <div class="left-titleborder bggray blue hidden-phone border-rad5">Featured Products</div>
          <div class="featured-seller">
            <div class="mar5">
              <div class="fea-sell-w">
                <div class="fea-sell-img">
                  <img src="$CDN$images/seller1.png" />
                </div>
                <div class="fea-selr">
                  <span class="fea-sell-n">Top Factory of Electronic Cigarette</span>
                  <div class="prod-pricef">$29.95</div>
                  <a class="btn-cart" href="">
                    <img src="$CDN$images/btn-add-cart.png" />
                  </a>
                </div>
              </div>
              <div class="cl"></div>
            </div>
            <div class="mar5">
              <div class="fea-sell-w">
                <div class="fea-sell-img">
                  <img src="$CDN$images/seller2.png" />
                </div>
                <div class="fea-selr">
                  <span class="fea-sell-n">Top Factory of Electronic Cigarette</span>
                  <div class="prod-pricef">$29.95</div>
                  <a class="btn-cart" href="">
                    <img src="$CDN$images/btn-add-cart.png" />
                  </a>
                </div>
              </div>
              <div class="cl"></div>
            </div>
            <div class="mar5">
              <div class="fea-sell-w">
                <div class="fea-sell-img">
                  <img src="$CDN$images/seller3.png" />
                </div>
                <div class="fea-selr">
                  <span class="fea-sell-n">Top Factory of Electronic Cigarette</span>
                  <div class="prod-pricef">$29.95</div>
                  <a class="btn-cart" href="">
                    <img src="$CDN$images/btn-add-cart.png" />
                  </a>
                </div>
              </div>
              <div class="cl"></div>
            </div>
            <div class="mar5">
              <div class="fea-sell-w">
                <div class="fea-sell-img">
                  <img src="$CDN$images/seller4.png" />
                </div>
                <div class="fea-selr">
                  <span class="fea-sell-n">Top Factory of Electronic Cigarette</span>
                  <div class="prod-pricef">$29.95</div>
                  <a class="btn-cart" href="">
                    <img src="$CDN$images/btn-add-cart.png" />
                  </a>
                </div>
              </div>
              <div class="cl"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="grid9">
        <div class="mar5 visible-phone">
          <div class="pad5">
            <img src="$CDN$images/home-16.png" />
              &gt; Entertainment &gt; Gaming &gt;
              <div class="cl"></div>
            </div>
          <div class="mobiletitle"> Game Assecessories </div>
        </div>
        <div style="overflow:hidden; border:1px solid #ccc !important" class="mar5 hidden-phone border-rad5">
          <img width="100%" src="$CDN$images/slide.jpg" /> </div>
        <div class="box5 mar5 hidden-phone border-rad5">
          <div class="blue pad10 bggray">
            Welcome to Conceptronic online
            <div class="cl"></div>
          </div>
          <div class="mar5">
            <p>
              Conceptronic is constantly innovating, designing classy and convenient solutions to ensure your technology is always cutting edge and up to date. We pride
              ourselves on stylish design, quality engineering and clever, accessible products for the home or office. To receive the latest word on innovation from Conceptronic,
              subscribe to our newsletter. The team is always working to stay ahead, striving to provide the right solution at the right price for all your technology needs.
            </p>
          </div>
        </div>
        <div class="mar5 pad5 visible-phone">
          <a class="listview" href="">
            <span class="viewtext"></span>
          </a>
          <a class="gridview" href="">
            <span class="viewtext"></span>
          </a>
          <a class="settings" href="">
            <span class="viewtext"></span>
          </a>
          <div class="shortby">
            <select class="shortby-select">
              <option>Position</option>
            </select>
          </div>
          <div class="cl"></div>
        </div>
        <!--<div class="product-wrap">
          <div class="box1 mar5">
            <div id="imgcontainer"><img src="images/dummy-img8.png"></div>
            <div class="prod-name">SONY VAIO VGN Netbook PC</div>
            <div class="prod-desc">Product description Product descriptionProduct descriptionProduct</div>
            <div class="prod-price">$29.95</div>
            <a href="" class="btn-cart"><img src="images/btn-add-cart.png"></a>
            <div class="cl"></div>
          </div>
        </div>-->
        <div class="product-wrap">
          <div class="product-box mar5">
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-pro-image.jpg" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC-VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price">$29.95</div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-add-cart.png" />
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="product-wrap">
          <div class="mar5 product-box">
            <div class="prod"></div>
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-pro-image1.jpg" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC-VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price"></div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-more-info.png"/>
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="product-wrap">
          <div class="mar5 product-box">
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-img3.png" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price">$29.95</div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-add-cart.png" />
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="product-wrap">
          <div class="mar5 product-box">
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-img8.png" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC-VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price">$29.95</div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-add-cart.png" />
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="product-wrap">
          <div class="mar5 product-box">
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-pro-image.jpg" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price">$29.95</div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-add-cart.png" />
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="product-wrap">
          <div class="mar5 product-box">
            <div class="prod"></div>
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-pro-image1.jpg" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price">$29.95</div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-add-cart.png" />
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="product-wrap">
          <div class="mar5 product-box">
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-img3.png" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price">$29.95</div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-add-cart.png" />
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
        <div class="product-wrap">
          <div class="mar5 product-box">
            <div class="prod"></div>
            <div id="imgcontainer">
              <img src="$CDN$images/dummy-pro-image1.jpg" />
            </div>
            <div class="prod-name">SONY VAIO VGN Netbook PC</div>
            <div class="prod-desc">SHORT DESCRIIPTIONS</div>
            <div class="prod-desc">Description Text Goes Here Description Text Goes HereDescription Text Goes</div>
            <div class="prod-price">$29.95</div>
            <div class="cartbtn-wrap">
              <a class="btn-cart" href="">
                <img src="$CDN$images/btn-add-cart.png" />
              </a>
            </div>
            <div class="cl"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="cl"></div>
  </section>
  <div class="footer">
    <div class="newsletter-ph visible-phone">
      <div class="mar5 mob-news">
        <div class="footer-title">Newsletter Sign Up</div>
        <p>Recievce Latest product updates and releases</p>
        <input type="text" class="fld-newsletter-ph" />
          <input type="button" value="Sign Up" class="btn-newsletter-ph" />
      </div>
      <div class="cl"></div>
    </div>
    <div class="contrant hidden-phone">
      <div class="grid2">
        <div class="mar5">
          <div class="footer-title">Product Categories</div>
          <ul class="footer-link">
            <li>
              <a href="">Speaker</a>
            </li>
            <li>
              <a href="">Keyboard &amp; Mouse</a>
            </li>
            <li>
              <a href="">Webcam &amp; Microphone</a>
            </li>
            <li>
              <a href="">Webcam</a>
            </li>
            <li>
              <a href="">Microphone</a>
            </li>
            <li>
              <a href="">Headset &amp; Headphone</a>
            </li>
            <li>
              <a href="">USB Hub &amp; Cardreader</a>
            </li>
            <li>
              <a href="">HDD dock &amp; Enclosure</a>
            </li>
            <li>
              <a href="">Power Solutions</a>
            </li>
            <li>
              <a href="">Interface Card</a>
            </li>
            <li>
              <a href="">USB sharing</a>
            </li>
            <li>
              <a href="">Audio &amp; Video Solution</a>
            </li>
            <li>
              <a href="">Locker &amp; Cooling Pad</a>
            </li>
            <li>
              <a href="">Sleeve &amp; Bag</a>
            </li>
            <li>
              <a href="">Cleaning Solution</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="grid2">
        <div class="mar5">
          <div class="footer-title">Conceptonic Store</div>
          <ul class="footer-link">
            <li>
              <a href="">About Us</a>
            </li>
            <li>
              <a href="">Online Catalogue / Downloads</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="grid2">
        <div class="mar5">
          <div class="footer-title">Wagner Online Info</div>
          <ul class="footer-link">
            <li>
              <a href=""> Wagner Online Main Site</a>
            </li>
            <li>
              <a href="">About Us</a>
            </li>
            <li>
              <a href="">Contact Us</a>
            </li>
            <li>
              <a href="">Shipping Details</a>
            </li>
            <li>
              <a href="">My Account</a>
            </li>
            <li>
              <a href="">Terms and Conditions</a>
            </li>
            <li>
              <a href="">Privacy Policy</a>
            </li>
            <li>
              <a href="">Browse Keyword Index</a>
            </li>
            <li>
              <a href="">Browse Product Tag Index</a>
            </li>
            <li>
              <a href="">Site Map</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="grid2">
        <div class="mar5">
          <div class="footer-title">Wagner Online Stores Sites</div>
          <ul class="footer-link">
            <li>
              <a href="">Conceptronic Online Store</a>
            </li>
            <li>
              <a href="">Aerpro Online Store</a>
            </li>
            <li>
              <a href="">Benelec Online Store</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="grid2  hidden-phone">
        <div class="mar5">
          <div class="footer-title">Share</div>
          <ul class="footer-link-img">
            <li>
              <a href="">
                <img src="$CDN$images/facebook.png"/>
              </a>
            </li>
            <li>
              <a href="">
                <img src="$CDN$images/twitter.png" />
              </a>
            </li>
            <li>
              <a href="">
                <img src="$CDN$images/pinterest.png" />
              </a>
            </li>
          </ul>
          <ul class="footer-link-img">
            <li>
              <a href="">
                <img src="$CDN$images/googleplus.png" />
              </a>
            </li>
            <li>
              <a href="">
                <img src="images/linkedin.png" />
              </a>
            </li>
            <li>
              <a href="">
                <img src="$CDN$images/email.png" />
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="grid2 hidden-phone">
        <div class="mar5">
          <div class="footer-title">Payment Options</div>
          <ul class="footer-link-img">
            <li>
              <a>
                <img src="$CDN$images/mastercard.jpg" />
              </a>
            </li>
            <li>
              <a>
                <img src="$CDN$images/americanexpress.jpg" />
              </a>
            </li>
          </ul>
          <ul class="footer-link-img">
            <li>
              <a>
                <img src="$CDN$images/visa.jpg" />
              </a>
            </li>
            <li>
              <a>
                <img src="$CDN$images/paypal.jpg" />
              </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="cl"></div>
      <div class="grid4 fright newsletter hidden-phone">
        <div class="mar5">
          <div class="footer-title">Newsletter Sign Up</div>
          <p>Recievce Latest product updates and releases</p>
          <div class="grid9">
            <input type="text" class="fld-newsletter" id="txtMail">
          </div>
          <div class="grid3">
            <a href="#" onclick="GetDeal(); return false;" class="btn-newsletter">Sign Up</a>
            <!--<input type="button" value="Sign Up" class="btn-newsletter">-->
          </div>
        </div>
      </div>
      <span class="copy">&copy; 2014 Wagner Online Store. All Rights Reserved.</span>
    </div>
    <div class="contrant visible-phone">
      <div id="footeraccordian">
        <ul>
          <!-- we will keep this LI open by default -->
          <li>
            <h3>
              <span></span>Conceptonic Store
            </h3>
            <ul>
              <li>
                <a href="">About Us</a>
              </li>
              <li>
                <a href="">Online Catalogue / Downloads</a>
              </li>
            </ul>
          </li>
          <li>
            <h3>
              <span></span>Wagner Online Info
            </h3>
            <ul>
              <li>
                <a href=""> Wagner Online Main Site</a>
              </li>
              <li>
                <a href="">About Us</a>
              </li>
              <li>
                <a href="">Contact Us</a>
              </li>
              <li>
                <a href="">Shipping Details</a>
              </li>
              <li>
                <a href="">My Account</a>
              </li>
              <li>
                <a href="">Terms and Conditions</a>
              </li>
              <li>
                <a href="">Privacy Policy</a>
              </li>
              <li>
                <a href="">Browse Keyword Index</a>
              </li>
              <li>
                <a href="">Browse Product Tag Index</a>
              </li>
              <li>
                <a href="">Site Map</a>
              </li>
              <li>
                <a href="">Brand MicroSite</a>
              </li>
            </ul>
          </li>
          <li>
            <h3>
              <span></span>Wagner Online Stores Sites
            </h3>
            <ul>
              <li>
                <a href="">Conceptronic Online Store</a>
              </li>
              <li>
                <a href="">Aerpro Online Store</a>
              </li>
              <li>
                <a href="">Benelec Online Store</a>
              </li>
            </ul>
          </li>
        </ul>
      </div>
      <span class="copy">&amp;copy; 2014 Wagner Online Store. All Rights Reserved.</span>
    </div>
    <div class="cl"></div>
  </div>
  <div id="pageslide" style="display: none;"></div>
</div>