

<div class="home-grid">
  <div class="grid-img">
    <a href="$TBT_REWRITEURL$/bb/"   class="hoverblack">
      <img class="lazy" data-original="$CDNROOT$$TBT_IMAGE_FILE$" src="$CDNROOT$$TBT_IMAGE_FILE$"   alt="$TBT_TOSUITE_MODEL1$"/>
    </a>
  </div>
  <div class="grid-detail2" style="vertical-align:middle">
    <h5>
      <a href="$TBT_REWRITEURL$/bb/" style="font-size:15px;">
       $TBT_TOSUITE_MODEL1$
      </a>
    </h5>
  </div>
</div >