<li class="padding_10 border_bottom padding_bottom15 padding_top15">

  <div class="pull-left">
    <img src="$CDNROOT$prodimages$TWebImage1$" class="pull-left" height="50px" width="50px" />
                        </div>
  <div class="pull-left margin_left15 drop_width">
    <a href="$TBT_REWRITEURL$">
      <div>
        <strong>Order-Code : $CODE$ </strong>
      </div>
      <div>
        $FAMILY_NAME$
      </div>

      <div class="green_clr margin_top">
        <strong>Price : &#36; $COST$ </strong>
      </div>
    </a>
  </div>
  <div class="clear"></div>
</li>
