<div class="product-left">
  <div class="newpro_name">
    <a href="$TBT_REWRITEURL_FAMILY$/fl/">
        <h5>$TBT_FAMILY_NAME$</h5>
    </a>
  
  </div>
  <div class="newpro-img">
    <!--<img class="img-responsive" src="/prodimages$TBT_TWEB_IMAGE1$"/>-->
    <img class="img-responsive" src="$TBT_TWEB_IMAGE1$"/>
  </div>
  <div class="newpro_code">
    <a href="$TBT_REWRITEURL$/pd/">
      <p style="font-size:12px">$TBT_CODE$</p>
    </a>
  </div>
</div>
