<h3>&#36;9.90 Australia Wide Flat Rate Shipping*</h3>
        <p>
          No matter where you are located in Australia we offer flat rate shipping.
          Some conditions apply, <br />
            please see our <a href="/Termsandconditions.aspx">Terms and Conditions </a>page.
        </p>

        <h3>Store Pick Up from Sydney Showroom</h3>
        <p>
          Goods can be picked from our premises from 8.30AM to 5.00PM Monday to Friday and from 9AM till 4PM on Saturday.<br />
            In order to avoid delays it is recommended that you place your order 2 hours prior to pick up.
            please see our <br />
Terms and Conditions page for more details.</p>

        <h3>International Order Shipping Available</h3>
        <p>
          We ship internationally. Once your order is received we will advise shipping cost to you by email.<br />
 Your order will be updated with the freight cost.</p>