
<table align="center" width="100%" border="0" cellpadding="0" cellspacing="0" class="border_1">
  <tr>
    <td valign="bottom">
      <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tx_1">
        <tr height="35">
          <td>
            <table width="100%" border="0" cellpadding="0" cellspacing="0" class="tx_1">
              <tr>
              <td height="39" vAlign="top" width="11">
                <img alt="" src="$CDN$Images/Fr_Cr_5.png" width="11" height="39" />
              </td>
              <td style="BACKGROUND-IMAGE: url($CDN$Images/Fr_center_1.png); BACKGROUND-REPEAT: repeat-x" class="txt_14" height="39" width="550" align="left">
                <img hspace="10" alt="" src="$CDN$Images/downarrow_G.png" width="24" height="12" /> $TBW_CATEGORY_NAME$ 
              </td>
              <td height="39" vAlign="top" width="10">
                <img alt="" src="$CDN$Images/Fr_Cr_6.png" width="10" height="39" /> 
            </td>
              </tr>
            </table>
          </td>         
        </tr>       
      </table>
    </td>
  </tr>
  <tr style="display:$TBT_DISPLAY_LINK$;">
    <td>
      <table width="100%" bgColor="#f2f2f2" border="0" cellSpacing="0" cellPadding="0">
        <tr>
          <td align="left" height="25"  width="30">
          </td>
          <td align="left" height="25"  width="730">
            <span>
              <a href="$TBT_EBOOK_LINK$" target="_blank" style="color:Blue;float:left;display:$TBT_DISPLAY_EBOOK_LINK$;">View eBook &nbsp;&nbsp;&nbsp; - &nbsp;&nbsp;&nbsp;</a>
              <a href="Catalogue Download$PDF$" target="_blank" style="color:Blue;display:$TBT_DISPLAY_PDF_LINK$;">View PDF</a>
            </span>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td align="center">
      <iframe src="$TBT_ADV_URL_LINK$" border="0" frameborder="0" width="580" height="1000px" ></iframe>
    </td>
  </tr> 
</table>
