<html>
 <meta http-equiv="Content-Language" content="en-us">  
 <title>Order Awaiting Payment Notification</title>  </head> <body rightmargin="0"> 
 <table cellpadding="0" width="527" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0"> <tr> <td valign="top" height="64" width="525"> 
	<p style="font-size: x-large;"><b><span style="color:black">
	Order Awaiting Payment Notificaiton
	</b>
	</p>
	</td> </tr> <tr> <td valign="top" height="449" width="525"> <table cellpadding="0" cellspacing="0" border="0" width="490" height="439">  <tr> 
		<td height="439" style="width: 490px">  <table border="0" width="468" height="400" cellpadding="10" cellspacing="0"> <tr> <td valign="top" width="448"> <p align="left" style="margin-left: 3px"> <i><b><font face="Arial" size="4"> 
	<span lang="en-au" style="font-family: arial, Helvetica, sans-serif; font-size: 18px">
	<br>
	</span></font></b></i></p>
				
				<table style="width: 100%;border-collapse: collapse;">
							<tr>  <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p ><b><span style="color:black">
						  Web Site
						  </b>
						</p>
     
					  </td>
					  <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p><b><span style="color:black">
						  Customer No
	
	</b>
						
						</p>
					  </td>
					 <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p ><b><span style="color:black">
						WES Invoice No
						</b>
						</p>

					  </td>
					   <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p ><b><span style="color:black">
						 Cust. Order No.
						 </b>
						</p>

					  </td>
					    <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p ><b><span style="color:black">
						  Total Amount
						  </b>
						</p>

					  </td>
					    <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p><b><span style="color:black">
						 Web Order ID
						 </b>
						</p>

					  </td>
					    <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p ><b><span style="color:black">
						Company Name
						</b>
						</p>

					  </td>
					   <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p ><b><span style="color:black">
						User Name
						</b>
						</p>

					  </td>
					  <td style="width:61.0pt;border:solid windowtext 1.0pt;background:yellow;padding:0cm 5.4pt 0cm 5.4pt;height:15.0pt" width="81" valign="bottom" nowrap="">
						<p ><b><span style="color:black">
						Modified Time
						</b>
						</p>

					  </td>

					</tr>

								$TBWDataList:{
        $it.TBWDataListItem$}$
						</table>	
						
						<br>
					
		 </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </body> </html>

