<tr>
  <td style="font-family:'Lucida Sans','Lucida Sans Regular','Lucida Grande','Lucida Sans Unicode',Geneva,Verdana,sans-serif;font-size:14px;font-weight:normal;border:1px solid #d7d7d7;width:237px;padding-left:10px;height:35px">
    <a href="$siteurl$$url$" style="text-decoration: none;">
    <img src="http://staging.wagneronline.com.au$Image$" alt="img" style="max-width:100px;max-height:100px;" />
    </a>
  </td>
  <td style="font-family:'Lucida Sans','Lucida Sans Regular','Lucida Grande','Lucida Sans Unicode',Geneva,Verdana,sans-serif;font-size:14px;font-weight:normal;border:1px solid #d7d7d7;width:237px;padding-left:10px;height:35px">
    <a href="$siteurl$$url$" style="text-decoration: none;font-size: 12px;">
      $Fname$
    </a>
  </td>
  <td style="font-family:'Lucida Sans','Lucida Sans Regular','Lucida Grande','Lucida Sans Unicode',Geneva,Verdana,sans-serif;font-size:14px;font-weight:normal;border:1px solid #d7d7d7;width:237px;padding-left:10px;height:35px">
    <a href="$siteurl$$url$" style="text-decoration: none;font-size: 12px;">
      $Desc$
    </a>
  </td>
  <td style="font-family:'Lucida Sans','Lucida Sans Regular','Lucida Grande','Lucida Sans Unicode',Geneva,Verdana,sans-serif;font-size:14px;font-weight:normal;border:1px solid #d7d7d7;width:237px;padding-left:10px;height:35px">
    <a href="$siteurl$$url$" style="text-decoration: none;font-size: 12px;">
      $Price$
    </a>
  </td>
</tr>