<tr>
  <td style="font-family:'Lucida Sans','Lucida Sans Regular','Lucida Grande','Lucida Sans Unicode',Geneva,Verdana,sans-serif;font-size:14px;font-weight:normal;border:1px solid #d7d7d7;width:237px;padding-left:10px;height:35px">
    $Code$
  </td>
  <td style="font-family:'Lucida Sans','Lucida Sans Regular','Lucida Grande','Lucida Sans Unicode',Geneva,Verdana,sans-serif;font-size:14px;font-weight:normal;border:1px solid #d7d7d7;width:237px;padding-left:10px;height:35px">
    $Qty$
  </td>
</tr>