<html><head>

<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Wagner New Customer</title>

<style>
<!--
div.Section1
	{page:Section1;}
.style1 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0091C7;
}
.style2 {
				font-family: Arial;
				font-size: 9pt;
				color: #FFFFFF;
}
.style3 {
				border-width: 1px;
				background-color: #0089BC;
}
.style4 {
				border-width: 1px;
}
.style6 {
				border-width: 1px;
				background-color: #FFFFFF;
}
.style7 {
				border-width: 1px;
				background-color: #009c52;
}
.style8 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #009c52;
}
.style9 {
				font-family: Arial;
				font-size: 9pt;
}
.style10 {
				border-width: 1px;
				background-color: #E0E0E0;
}

-->
</style>
</head>

<body rightmargin="0">
		<table cellpadding="0" width="527" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0">
	<tr>
		<td valign="top" height="64" width="525">
		<img alt="Wagner" src="http://wes.com.au/images/wagner_email_headers_chkout.gif" width="525" height="71"></td>
	</tr>
	<tr>
		<td valign="top" height="449" width="525">
		<table cellpadding="0" cellspacing="0" border="0" width="490" height="439">
			<!-- MSCellFormattingTableID="2" -->
			<tr>
				<td height="439" width="490">
				<!-- MSCellFormattingType="content" -->
				<table border="0" width="468" height="400" cellpadding="10" cellspacing="0">
					<tr>
						<td valign="top" width="448">

						<p style="font-size:14pt;color:#333333;font-family:arial,Helvetica,sans-serif;margin-top:25px;margin-bottom:20px;font-weight:bold">
		Your order is updated and ready to checkout!</p>

		<p style="font-family:arial,Helvetica,sans-serif;font-size:9pt;width:450px;margin-top:15px;margin-bottom:15px;line-height:18px">
		Thanks for your recent order. We have updated your order and it's 
		now awaiting payment. Payment can be made online by clicking on the button 
		below.</p>

		<table style="width:450px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse">
			<tbody><tr>
				<td colspan="3" style="border:1px solid #000000;height:30px;border-collapse:collapse;font-family:arial,Helvetica,sans-serif;font-size:9pt;background-color:#0092c8;color:#ffffff;padding-left:3px">
				Payment Required</td>
			</tr>
			<tr>
				<td style="border:1px solid #000000;height:40px;background-color:#ffffff;width:50%;border-collapse:collapse"> 
				<p style="font-family:arial,Helvetica,sans-serif;font-size:13pt;font-weight:700;color:#0089bc;margin-left:10px;margin-bottom:0px;margin-top:10px" align="left"> 
				Total: &#36;$AMOUNT$</p><p style="margin-left:11px;font-family:arial,Helvetica,sans-serif;font-size:9pt;margin-top:3px;margin-bottom:10px" align="left"> 
				Including Freight.</p><p></p></td>
				<td style="border:1px solid #000000;padding:0px 0px 0px 10px;height:40px;background-color:#ffffff;width:50%;border-collapse:collapse"> 
				<table style="width:91%;height:35px">
					<tbody><tr>
						<td style="background-color:#4dba62;font-family:arial,Helvetica,sans-serif;font-size:11pt;font-weight:bold;color:#ffffff;text-align:center;text-decoration:none;height:40px;width:210px">
						<a target="_blank" href="$PAY_METHOD$" style="font-family:arial,Helvetica,sans-serif;font-size:11pt;font-weight:bold;text-decoration:none;color:#ffffff" target="_blank">
						View Order &amp; Pay Now</a></td>
					</tr>
				</tbody></table>
				</td>
			</tr>
		</tbody></table>

											<p style="font-size:11pt;color:#333333;font-family:arial,Helvetica,sans-serif;margin-top:25px;margin-bottom:12px;font-weight:bold">
		Order Details</p>
		<table style="border-style:solid;border-width:1px;width:450px;border-collapse:collapse">
				<tbody><tr>
					<td colspan="3" style="border:1px solid #000000;height:25px;border-collapse:collapse;font-family:arial,Helvetica,sans-serif;font-size:9pt;background-color:#0092c8;color:#ffffff;padding-left:3px">
					Order Information</td>
				</tr>
				<tr>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:150px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#e0e0e0">
					Date</td>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:150px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#e0e0e0">
					Customer Order No</td>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:150px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#e0e0e0">
					Shipping Method</td>
				</tr>
				<tr>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:150px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px">
					$OrderDate$</td>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:150px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px">
					$CustOrderNo$</td>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:150px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px">
						$ShippingMethod$</td>
				</tr>
			</tbody></table>

			<br>
			<table style="border-style:solid;border-width:1px;width:450px;border-collapse:collapse">
				<tbody><tr>
					<td colspan="2" style="border:1px solid #000000;height:25px;border-collapse:collapse;font-family:arial,Helvetica,sans-serif;font-size:9pt;background-color:#0092c8;color:#ffffff;padding-left:3px">
					User Information</td>
				</tr>
				<tr>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#e0e0e0">
					Created By User</td>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#e0e0e0">
					Submitted By User</td>
				</tr>
				<tr>
					<td style="padding:5px 0px 5px 4px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px">
					$CreatedBy$
						</td>
					<td style="padding:5px 0px 5px 3px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px">
					$SubmittedBy$</td>
				</tr>
			</tbody></table>
			<br>
			<table style="border-style:solid;border-width:1px;width:450px;border-collapse:collapse">
				<tbody><tr>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#0089bc;color:#ffffff">
					Billing Details</td>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#0089bc;color:#ffffff">
					Shipping Details</td>
				</tr>
				<tr>
					<td style="padding:10px 0px 10px 6px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;vertical-align:top">
					$BillingAddress$ 
						</td>
					<td style="padding:10px 0px 10px 6px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px">
						$ShippingAddress$
						</td>
				</tr>
			</tbody></table>

					
		<br>
		$if(TBT_shippingnotes)$
	<table style="border-style:solid;border-width:1px;width:450px;border-collapse:collapse">
		<tbody><tr>
			<td style="border:1px solid #000000;height:25px;border-collapse:collapse;font-family:arial,Helvetica,sans-serif;font-size:9pt;background-color:#0092c8;color:#ffffff;padding-left:5px">
			Comments</td>
		</tr>
		<tr>
			<td style="padding:10px 0px 10px 5px;margin:0px;border:1px solid #000000;width:150px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:20px">
			$shippingnotes$</td>
		</tr>
	</tbody></table>
	<br>
	$endif$

			<table style="border-style:solid;border-width:1px;width:450px;border-collapse:collapse">
				<tbody><tr>
					<td colspan="2" style="border:1px solid #000000;height:25px;border-collapse:collapse;font-family:arial,Helvetica,sans-serif;font-size:9pt;background-color:#0092c8;color:#ffffff;padding-left:3px">
					Order Contents</td>
				</tr>
				<tr>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#e0e0e0">
					Order Code</td>
					<td style="padding:0px 0px 0px 3px;margin:0px;border:1px solid #000000;width:225px;font-family:arial,Helvetica,sans-serif;font-size:9pt;border-collapse:collapse;height:25px;background-color:#e0e0e0">
					QTY</td>
				</tr>
				$TBWDataList:{
		$it.TBWDataListItem$}$
		</tbody></table>

						
						<br>
						<p style="font-family:arial,Helvetica,sans-serif;font-size:9pt;width:450px">	
		Best Regards<br>
		Wagner Online<br>
		<br>
		Email: <a href="mailto:sales@wagneronline.com.au" target="_blank">sales@wagneronline.com.au</a><br>
		Phone: (+61) 02 9798 9233<br>
		</p>
			</td>
					</tr>
					</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	</table>
		</body>

</html>