










<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>Address Error</title>
<style>
<!--
div.Section1
	{page:Section1;}
.style1 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0091C7;
}
.style2 {
				font-family: Arial;
				font-size: 9pt;
				color: #FFFFFF;
}
.style3 {
				border-width: 1px;
				background-color: #0089BC;
}
.style4 {
				border-width: 1px;
}
.style6 {
				border-width: 1px;
				background-color: #FFFFFF;
}
.style7 {
				border-width: 1px;
				background-color: #0092C8;
}
.style8 {
				font-family: Arial, Helvetica, sans-serif;
				font-size: x-small;
				border-width: 1px;
				background-color: #0092C8;
}
.style9 {
				font-family: Arial;
				font-size: 9pt;
}
.style10 {
				border-width: 1px;
				background-color: #E0E0E0;
}
-->
</style>
</head>
<body>
<div>

<table style="padding: 0px; margin: 0px; width: 530px; border: 1px solid #333333; border-collapse: collapse">
	<tr>
		<td style="border: 1px solid #333333; padding: 0px; margin: 0px; border-collapse: collapse">
		<a target="_blank" href="http://www.wagneronline.com.au" style="height: 75px;display: block;">
		<img alt="wagner" img border="0" src="https://www.wagneronline.com.au/mp/email/template/wagnerheader.gif"  class="newStyle1" style="border-width: 0px; top: 10px;width:60%;padding:1%"   /></a></td>
	</tr>
	<tr>
		<td style="border: 1px solid #333333; padding: 0px 0px 0px 20px; margin: 0px; border-collapse: collapse">
		<br />
		
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 30px;">
		Dear Customer,</p>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt">
Your Address information has not been update in our system due to technical error.<br/>
Kindly update your address in http://wagneronline.com.au/login.aspx <br/>
Sorry for the inconvenience.
</p>
	
		
		
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 35px;">
		Best Regards<br />
		BIGTOP<br>
		<br />
		Phone:  (02) 9798 9233<br />
		Email: <a href="mailto:sales@wagneronline.com.au">
		sales@wagneronline.com.au</a><br />
		Web: <a href="http://www.wagneronline.com.au">
		http://www.wagneronline.com.au</a><br />
		&nbsp;</p>
		<p style="font-family: arial, Helvetica, sans-serif; font-size: 10pt; margin-top: 30px;">
		&nbsp;</p>
		<p></p></td>
	</tr>
</table>
</div>


</body></html>