<html>
 <meta http-equiv="Content-Language" content="en-us">  
 <title>Wagner Payment Notification</title>  </head> <body rightmargin="0"> <table cellpadding="0" width="527" height="520" style="border-collapse: collapse" border="1" bordercolor="#000000" cellspacing="0"> <tr> <td valign="top" height="64" width="525"> 
	<img alt="WAGNER" src="http://wagneronline.com.au/images/wagner_Paymentnotification.gif" width="525" height="71"></td> </tr> <tr> <td valign="top" height="449" width="525"> <table cellpadding="0" cellspacing="0" border="0" width="490" height="439">  <tr> 
		<td height="439" style="width: 490px">  <table border="0" width="468" height="400" cellpadding="10" cellspacing="0"> <tr> <td valign="top" width="448"> <p align="left" style="margin-left: 3px"> <i><b><font face="Arial" size="4"> 
	<span lang="en-au" style="font-family: arial, Helvetica, sans-serif; font-size: 18px">
	<br>
	Your order is updated and ready to checkout!</span></font></b></i></p>
						<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt; line-height: 18px; margin-bottom: 25px;"> 
						Thanks for your recent order at Wagner Online. <br>
						We have now updated your order with freight costs and 
						now awaiting payment.<br>
						If  
	any incorrect details are found or if you have any concerns please contact us.<br> 
						<b><br>
						Email:</b> <a href="mailto:sales@wagneronline.com.au">
	sales@wagneronline.com.au</a><br> <b>Phone:</b>(+61) 02-9798-9233 <br> <b>
	Fax:</b> (+61) 02-9798-0017</p> 
						
						<table style="width: 100%" align="center">
							<tr>
								<td colspan="3" style="border-style: solid; border-width: 1px; height: 30px; background-color: #0092C8">
								<p align="left" style="font-family: arial, Helvetica, sans-serif; font-size: 9pt; margin-left: 3px; color: #FFFFFF;"> 
								Payment Required</td>
							</tr>
							<tr>
								<td style="border-style: solid; border-width: 1px; height: 40px; background-color: #FFFFFF; width: 33%;"> 
								<p align="left" style="font-family: arial, Helvetica, sans-serif; font-size: 12pt; font-weight: 700; color: #0089BC; margin-left: 10px; margin-bottom: 0px; margin-top: 10px;"> 
								Total: 
								&#36; $AMOUNT$<p align="left" style="margin-left: 11px; font-family: arial, Helvetica, sans-serif; font-size: 9pt; margin-top: 3px; margin-bottom: 10px;"> 
								Including Freight.</td>
								<td style="border-style: solid; border-width: 1px; height: 40px; background-color: #FFFFFF; width: 33%;"> 
								<p align="left" style="font-family: arial, Helvetica, sans-serif; font-size: 12pt; font-weight: 700; color: #0089BC; margin-left: 10px; margin-bottom: 0px; margin-top: 10px;"> 
								Invoice No.
								<p align="left" style="margin-left: 11px; font-family: arial, Helvetica, sans-serif; font-size: 9pt; margin-top: 3px; margin-bottom: 10px;"> 
								WAG$INVOICENO$</td>
								<td style="padding: 0px 0px 0px 10px; border-style: solid; border-width: 1px; height: 40px; background-color: #FFFFFF; width: 33%; "> 
								<table style="width: 91%; height: 35px">
									<tr>
										<td style="background-color: #4DBA62; font-family: arial, Helvetica, sans-serif; font-size: 11pt; font-weight: bold; color: #FFFFFF; text-align: center; text-decoration: none">
										<a target="_blank" href="$PAY_METHOD$" style="font-family: arial, Helvetica, sans-serif; font-size: 12pt; font-weight: bold; text-decoration: none; color: #FFFFFF">
										View Order &amp; Pay Now</a></td>
									</tr>
								</table>
								</td>
							</tr>
						</table>
					
					<br>
						<table style="width: 100%">
							<tr>
								<td colspan="3" style="border-style: solid; border-width: 1px; height: 25px; background-color: #0092C8">
								<p align="left" style="font-family: arial, Helvetica, sans-serif; font-size: 9pt; margin-left: 3px; color: #FFFFFF;"> 
								Order Information</td>
							</tr>
							<tr>
								<td style="border-style: solid; border-width: 1px; height: 25px; background-color: #E0E0E0; width: 150px;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								Date</td>
								<td style="border-style: solid; border-width: 1px; height: 25px; background-color: #E0E0E0; width: 150px;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								Customer Order No</td>
								<td style="border-style: solid; border-width: 1px; height: 25px; background-color: #E0E0E0; width: 150px;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								Web Order ID</td>
							</tr>
							<tr>
								<td style="border-style: solid; border-width: 1px; height: 25px">
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								$OrderDate$</td>
								<td style="border-style: solid; border-width: 1px; height: 25px">
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								$CustOrderNo$</td>
								<td style="border-style: solid; border-width: 1px; height: 25px">
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								WAG$ORDER_ID$</td>
							</tr>
						</table>
						<br>
						<table style="width: 100%">
							<tr>
								<td style="border-style: solid; border-width: 1px; height: 25px; background-color: #0092C8; width: 50%;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt; color: #FFFFFF;"> 
								Billing Details</td>
								<td style="border-style: solid; border-width: 1px; height: 25px; background-color: #0092C8; width: 50%;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt; color: #FFFFFF;"> 
								Shipping Details</td>
							</tr>
							<tr>
								<td style="border-style: solid; border-width: 1px; height: 110px; background-color: #FFFFFF; width: 50%;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								<font face="Arial">
				$BillingAddress$ </font></td>
								<td style="border-style: solid; border-width: 1px; height: 110px; background-color: #FFFFFF; width: 50%; text-align: center;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								<font face="Arial">
				$ShippingAddress$ </font></td>
							</tr>
						</table>
					<br>
						<table style="width: 100%">
							<tr>
								<td colspan="2" style="border-style: solid; border-width: 1px; height: 25px; background-color: #0092C8">
								<p align="left" style="font-family: arial, Helvetica, sans-serif; font-size: 9pt; margin-left: 3px; color: #FFFFFF;"> 
								Order Contents</td>
							</tr>
							<tr>
								<td style="border-style: solid; border-width: 1px; height: 25px; background-color: #E0E0E0; width: 150px;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								Order Code</td>
								<td style="border-style: solid; border-width: 1px; height: 25px; background-color: #E0E0E0; width: 150px;"> 
								<p align="left" style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;"> 
								Qty</td>
							</tr>
								$TBWDataList:{
        $it.TBWDataListItem$}$
						</table>
						<br>
					
			<p align="left" style="font-family: arial, Helvetica, sans-serif; font-size: 9pt; left: 3px; line-height: 18px;"> <font size="2" face="Arial">
		Best Regards,<br> WAGNER Team</font></p> </td> </tr> </table> </td> </tr> </table> </td> </tr> </table> </body> </html>

