<tr><td bordercolor="#000000" height="20" style="width: 220px;border: 1px solid #000;" class="style6">
  <p align="left" style="margin-left: 3px"><font face="Arial" style="font-size: 9pt">
    <span lang="en-au">$Code$</span></font></td><td bordercolor="#000000" height="20" style="border: 1px solid #000;" class="style6">
      <p align="left" style="margin-left: 3px"><font face="Arial" style="font-size: 9pt"><span lang="en-au">$Qty$</span></font></td></tr>
			