<tr>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $WebSite$
    </p>
     
  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $CustomerNo$
    </p>
  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $WESInvoiceNo$
    </p>

  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $CustOrderNo$
    </p>

  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      &#36; $TotalAmount$
    </p>

  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $WebOrderID$
    </p>

  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $CompanyName$
    </p>

  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $UserName$
    </p>

  </td>
  <td style="border-style: solid; border-width: 1px; height: 25px">
    <p  style="margin-left: 3px; font-family: arial, Helvetica, sans-serif; font-size: 9pt;" align="left">
      $ModifiedTime$
    </p>

  </td>
</tr>
