<td align="center" valign="top" >
  <table width="312" border="0" cellspacing="0" cellpadding="0">
    <tr>
      <td height="200" valign="top" class="back_8">
        <table width="312" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td height="30" align="left">
              <div class="padding2">$TBT_PARENT_CATEGORY_NAME$</div>
            </td>
          </tr>
          <tr>
            <td height="165" align="center" valign="top">
              <table width="300" border="0" cellpadding="5" cellspacing="0">
                <tr valign="top">
                  <td width="107" height="170" valign="middle" align="left">$TBT_SUB_CATEGORY_LIST$</td>
                  <td width="7"  valign="top" class="bdr_left">
                  </td>
                  <td width="107"  height="170" valign="middle" >
                    $TBT_SUB_CATEGORY_LIST1$
                 
                  </td>
                </tr>
                <tr>
                  <td valign="bottom" align="left">
                    <a href="$TBT_CURRENTURL$ct.aspx?$TBT_REWRITEURL$"  class="tx_3 curpoi">
                      <strong>Click here </strong><!--<br/>--> &nbsp; to See Full List
                    </a>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td valign=top class="back_8_bottom" height=7> </td>
    </tr>
  </table>
</td>