<li class="padding_10 border_bottom padding_bottom15 padding_top15" style=" padding-bottom: 15px; padding-top: 15px;padding: 10px;border-bottom: thin solid #ddd;">

  <div class="pull-left">
    <img src="$TWebImage1$" class="pull-left" height="50px" width="50px" />
                        </div>
  <div class="pull-left margin_left15 drop_width">
    <a href="$TBT_REWRITEURL$" style="text-align:left; text-decoration:none; color:#333; padding:0px; display:block;" rel="nofollow">
      <div>
        <strong>Order-Code : $CODE$ </strong>
      </div>
      <div>
        $FAMILY_NAME$
      </div>

      <div class="green_clr margin_top">
        <strong>Price : &#36; $COST$ </strong>
      </div>
    </a>
  </div>
  <div class="clear"></div>
</li>
